import { Theme } from '@/types/theme';

export const BUSINESS_THEMES: Theme[] = [
  {
    id: 'COMPANY_INTRO',
    name: '회사 소개',
    nameEn: 'Company Introduction',
    icon: '🏢',
    emoji: '💼',
    description: '전문적인 회사 소개 영상',
    category: 'business',
    subCategory: 'corporate',
    colors: {
      primary: '#1E3A8A',
      secondary: '#2563EB',
      accent: '#3B82F6',
      background: '#EFF6FF',
      text: '#1E3A8A',
      gradient: 'linear-gradient(135deg, #1E3A8A 0%, #3B82F6 100%)',
    },
    fonts: {
      title: 'Pretendard',
      body: 'Pretendard',
      accent: 'Pretendard',
    },
    defaultMusic: 'corporate-professional',
    defaultTransition: 'slideLeft',
    defaultEffect: 'kenburns-pan-right',
    titleTemplate: '{company} 회사 소개',
    defaultEnding: '함께 성장하는 {company} 🏢\n더 나은 미래를 만들어갑니다',
    narrationPrompt: `당신은 회사 소개 영상의 전문적인 나레이터입니다.
회사의 비전, 성과, 역량을 신뢰감 있게 전달하세요.
전문적이고 자신감 있는 톤으로 진행하세요.`,
    narrationStyle: 'professional, confident, trustworthy',
    suggestedDuration: 120,
    suggestedPhotoCount: { min: 20, max: 50 },
    tags: ['회사소개', '기업', '비즈니스', '프로페셔널', 'IR'],
    premium: true,
    introStyles: [
      { type: 'cinematic', duration: 5, elements: ['title', 'logo', 'gradient-bg'], animation: { titleDelay: 1, subtitleDelay: 2.5, easing: 'easeInOut' } },
      { type: 'reveal', duration: 5, elements: ['title', 'subtitle'], animation: { titleDelay: 0.5, subtitleDelay: 2, easing: 'easeOut' } },
      { type: 'slide-up', duration: 4, elements: ['title', 'logo', 'gradient-bg'], animation: { titleDelay: 0.5, subtitleDelay: 1.5, easing: 'easeOut' } },
    ],
    outroStyles: [
      { type: 'fade-out', duration: 5, elements: ['message', 'logo', 'social'], animation: { messageDelay: 0, photosDelay: 2, easing: 'easeInOut' } },
      { type: 'zoom-out', duration: 4, elements: ['message', 'logo'], animation: { messageDelay: 0.5, photosDelay: 2, easing: 'easeOut' } },
    ],
    introPrompts: [
      '혁신과 성장의 여정',
      '신뢰받는 파트너',
      '미래를 함께 만들어가는 기업',
    ],
    outroPrompts: [
      '함께 성장하는 미래',
      '파트너십을 기대합니다',
      '새로운 가능성을 열어갑니다',
    ],
  },
  {
    id: 'TEAM_BUILDING',
    name: '팀빌딩/워크샵',
    nameEn: 'Team Building',
    icon: '🤝',
    emoji: '💪',
    description: '팀워크를 다지는 시간',
    category: 'business',
    subCategory: 'event',
    colors: {
      primary: '#059669',
      secondary: '#10B981',
      accent: '#34D399',
      background: '#ECFDF5',
      text: '#064E3B',
      gradient: 'linear-gradient(135deg, #059669 0%, #34D399 100%)',
    },
    fonts: {
      title: 'GmarketSans',
      body: 'Pretendard',
      accent: 'GmarketSans',
    },
    defaultMusic: 'teamwork-upbeat',
    defaultTransition: 'slideRight',
    defaultEffect: 'kenburns-pan-left',
    titleTemplate: '{team} 팀빌딩 {year}',
    defaultEnding: '함께해서 더 강해졌습니다! 🤝\n{team} 팀 화이팅! 💪',
    narrationPrompt: `당신은 팀빌딩/워크샵 영상의 활기찬 나레이터입니다.
팀워크와 협동의 가치를 생동감 있게 전달하세요.
활기차고 긍정적인 톤으로 진행하세요.`,
    narrationStyle: 'energetic, collaborative, positive',
    suggestedDuration: 90,
    suggestedPhotoCount: { min: 20, max: 50 },
    tags: ['팀빌딩', '워크샵', '팀워크', '협동', '회사'],
    premium: false,
    introStyles: [
      { type: 'dynamic-zoom', duration: 4, elements: ['title', 'subtitle', 'gradient-bg'], animation: { titleDelay: 0.3, subtitleDelay: 1.2, easing: 'easeOut' } },
      { type: 'split', duration: 4, elements: ['title', 'logo'], animation: { titleDelay: 0.5, subtitleDelay: 1.5, easing: 'easeOutBack' } },
    ],
    outroStyles: [
      { type: 'photo-collage', duration: 5, elements: ['message', 'photos'], animation: { messageDelay: 0.5, photosDelay: 0, easing: 'easeOut' } },
      { type: 'fireworks', duration: 4, elements: ['message'], animation: { messageDelay: 0.5, photosDelay: 2, easing: 'easeOut' } },
    ],
    introPrompts: [
      '함께해서 더 강해지는',
      '팀워크의 힘을 느끼는 시간',
      '하나가 되어 도전하다',
    ],
    outroPrompts: [
      '함께라서 가능했습니다',
      '앞으로도 함께 화이팅',
      '최고의 팀, 최고의 결과',
    ],
  },
  {
    id: 'CONFERENCE',
    name: '컨퍼런스/세미나',
    nameEn: 'Conference',
    icon: '🎤',
    emoji: '📊',
    description: '지식과 인사이트 공유',
    category: 'business',
    subCategory: 'event',
    colors: {
      primary: '#4F46E5',
      secondary: '#6366F1',
      accent: '#818CF8',
      background: '#EEF2FF',
      text: '#3730A3',
      gradient: 'linear-gradient(135deg, #4F46E5 0%, #818CF8 100%)',
    },
    fonts: {
      title: 'Pretendard',
      body: 'Pretendard',
      accent: 'Pretendard',
    },
    defaultMusic: 'conference-inspiring',
    defaultTransition: 'crossDissolve',
    defaultEffect: 'kenburns-zoom-out',
    titleTemplate: '{title} 컨퍼런스 {year}',
    defaultEnding: '함께한 인사이트의 시간! 🎤\n다음 컨퍼런스에서 만나요 📊',
    narrationPrompt: `당신은 컨퍼런스/세미나 영상의 전문적인 나레이터입니다.
지식 공유의 가치와 행사의 하이라이트를 전달하세요.
전문적이고 영감을 주는 톤으로 진행하세요.`,
    narrationStyle: 'professional, inspiring, knowledgeable',
    suggestedDuration: 120,
    suggestedPhotoCount: { min: 25, max: 60 },
    tags: ['컨퍼런스', '세미나', '발표', '지식공유', '네트워킹'],
    premium: true,
    introStyles: [
      { type: 'cinematic', duration: 5, elements: ['title', 'subtitle', 'logo', 'gradient-bg'], animation: { titleDelay: 1, subtitleDelay: 2.5, easing: 'easeInOut' } },
      { type: 'typewriter', duration: 5, elements: ['title', 'date'], animation: { titleDelay: 0, subtitleDelay: 2.5, easing: 'linear' } },
    ],
    outroStyles: [
      { type: 'scroll-credits', duration: 6, elements: ['message', 'credits', 'logo'], animation: { messageDelay: 0, photosDelay: 2, easing: 'linear' } },
      { type: 'thank-you', duration: 5, elements: ['message', 'social'], animation: { messageDelay: 0, photosDelay: 2, easing: 'easeInOut' } },
    ],
    introPrompts: [
      '지식과 인사이트가 만나는 순간',
      '함께 성장하는 네트워킹',
      '미래를 이끄는 아이디어',
    ],
    outroPrompts: [
      '영감 가득한 시간이었습니다',
      '다음 컨퍼런스에서 다시 만나요',
      '함께 나눈 지식, 함께 성장',
    ],
  },
  {
    id: 'PRODUCT_LAUNCH',
    name: '제품/서비스 출시',
    nameEn: 'Product Launch',
    icon: '🚀',
    emoji: '✨',
    description: '새로운 시작을 알리는 순간',
    category: 'business',
    subCategory: 'launch',
    colors: {
      primary: '#7C3AED',
      secondary: '#8B5CF6',
      accent: '#A78BFA',
      background: '#F5F3FF',
      text: '#5B21B6',
      gradient: 'linear-gradient(135deg, #7C3AED 0%, #A78BFA 100%)',
    },
    fonts: {
      title: 'Pretendard',
      body: 'Pretendard',
      accent: 'Pretendard',
    },
    defaultMusic: 'launch-exciting',
    defaultTransition: 'zoomIn',
    defaultEffect: 'kenburns-zoom-in',
    titleTemplate: '{product} 출시',
    defaultEnding: '새로운 경험이 시작됩니다! 🚀\n지금 바로 만나보세요 ✨',
    narrationPrompt: `당신은 제품/서비스 출시 영상의 나레이터입니다.
제품의 혁신성과 가치를 역동적으로 전달하세요.
흥미롭고 설득력 있는 톤으로 진행하세요.`,
    narrationStyle: 'exciting, innovative, persuasive',
    suggestedDuration: 90,
    suggestedPhotoCount: { min: 15, max: 40 },
    tags: ['출시', '런칭', '제품', '서비스', '혁신'],
    premium: true,
    introStyles: [
      { type: 'explosion', duration: 4, elements: ['title', 'logo', 'gradient-bg'], animation: { titleDelay: 0.3, subtitleDelay: 1.5, easing: 'easeOutBack' } },
      { type: 'glitch', duration: 4, elements: ['title', 'subtitle'], animation: { titleDelay: 0.3, subtitleDelay: 1.5, easing: 'easeOutExpo' } },
      { type: 'dynamic-zoom', duration: 4, elements: ['title', 'logo', 'particles'], animation: { titleDelay: 0.3, subtitleDelay: 1.2, easing: 'easeOut' } },
    ],
    outroStyles: [
      { type: 'fireworks', duration: 5, elements: ['message', 'logo', 'social'], animation: { messageDelay: 0.5, photosDelay: 2, easing: 'easeOut' } },
      { type: 'confetti', duration: 4, elements: ['message', 'qrCode'], animation: { messageDelay: 0.5, photosDelay: 1.5, easing: 'easeOut' } },
    ],
    introPrompts: [
      '새로운 혁신이 시작됩니다',
      '기대를 넘어선 경험',
      '미래가 지금 시작됩니다',
    ],
    outroPrompts: [
      '지금 바로 경험하세요',
      '새로운 시작을 함께',
      '당신의 삶을 바꿀 제품',
    ],
  },
  {
    id: 'COMPANY_PARTY',
    name: '회식/파티',
    nameEn: 'Company Party',
    icon: '🎉',
    emoji: '🍻',
    description: '함께 즐기는 시간',
    category: 'business',
    subCategory: 'party',
    colors: {
      primary: '#F59E0B',
      secondary: '#FBBF24',
      accent: '#FCD34D',
      background: '#FFFBEB',
      text: '#78350F',
      gradient: 'linear-gradient(135deg, #F59E0B 0%, #FCD34D 100%)',
    },
    fonts: {
      title: 'GmarketSans',
      body: 'Pretendard',
      accent: 'GmarketSans',
    },
    defaultMusic: 'party-fun',
    defaultTransition: 'slideRight',
    defaultEffect: 'kenburns-zoom-in',
    titleTemplate: '{team} 회식 {year}',
    defaultEnding: '즐거운 시간이었습니다! 🎉\n다음 모임도 기대해요 🍻',
    narrationPrompt: `당신은 회식/파티 영상의 밝은 나레이터입니다.
함께 즐긴 시간의 에너지와 유대감을 전달하세요.
밝고 유쾌한 톤으로 진행하세요.`,
    narrationStyle: 'fun, friendly, lively',
    suggestedDuration: 60,
    suggestedPhotoCount: { min: 15, max: 40 },
    tags: ['회식', '파티', '친목', '동료', '즐거움'],
    premium: false,
    introStyles: [
      { type: 'bounce', duration: 4, elements: ['title', 'subtitle', 'particles'], animation: { titleDelay: 0.3, subtitleDelay: 1.5, easing: 'easeOutBounce' } },
      { type: 'explosion', duration: 4, elements: ['title', 'gradient-bg'], animation: { titleDelay: 0.5, subtitleDelay: 1.5, easing: 'easeOutBack' } },
    ],
    outroStyles: [
      { type: 'confetti', duration: 4, elements: ['message', 'photos'], animation: { messageDelay: 0.5, photosDelay: 1.5, easing: 'easeOut' } },
      { type: 'photo-collage', duration: 5, elements: ['message', 'photos'], animation: { messageDelay: 0.5, photosDelay: 0, easing: 'easeOut' } },
    ],
    introPrompts: [
      '신나는 파티가 시작됩니다',
      '함께 즐기는 행복한 시간',
      '동료들과 함께하는 특별한 밤',
    ],
    outroPrompts: [
      '즐거운 시간이었습니다',
      '다음 모임도 기대해요',
      '함께해서 더 즐거웠어요',
    ],
  },
  {
    id: 'FAREWELL',
    name: '퇴사/송별',
    nameEn: 'Farewell',
    icon: '👋',
    emoji: '🌟',
    description: '새로운 시작을 응원합니다',
    category: 'business',
    subCategory: 'farewell',
    colors: {
      primary: '#6366F1',
      secondary: '#818CF8',
      accent: '#A5B4FC',
      background: '#EEF2FF',
      text: '#3730A3',
      gradient: 'linear-gradient(135deg, #6366F1 0%, #A5B4FC 100%)',
    },
    fonts: {
      title: 'GmarketSans',
      body: 'Pretendard',
      accent: 'GmarketSans',
    },
    defaultMusic: 'farewell-hopeful',
    defaultTransition: 'crossDissolve',
    defaultEffect: 'kenburns-zoom-in',
    titleTemplate: '{name}님 송별회',
    defaultEnding: '함께해서 행복했습니다! 👋\n새로운 곳에서도 화이팅! 🌟',
    narrationPrompt: `당신은 송별회 영상의 진심 어린 나레이터입니다.
함께한 시간에 대한 감사와 새로운 시작에 대한 응원을 담아주세요.
따뜻하고 응원하는 톤으로 진행하세요.`,
    narrationStyle: 'warm, supportive, hopeful',
    suggestedDuration: 90,
    suggestedPhotoCount: { min: 20, max: 50 },
    tags: ['송별', '퇴사', '새출발', '감사', '응원'],
    premium: false,
    introStyles: [
      { type: 'elegant-fade', duration: 5, elements: ['title', 'subtitle', 'gradient-bg'], animation: { titleDelay: 1, subtitleDelay: 2.5, easing: 'easeInOut' } },
      { type: 'floating', duration: 4, elements: ['title', 'particles'], animation: { titleDelay: 0.5, subtitleDelay: 1.5, easing: 'easeOutSine' } },
    ],
    outroStyles: [
      { type: 'wave-goodbye', duration: 5, elements: ['message', 'photos'], animation: { messageDelay: 0.5, photosDelay: 1.5, easing: 'easeOut' } },
      { type: 'flying-photos', duration: 5, elements: ['message', 'photos', 'credits'], animation: { messageDelay: 0.5, photosDelay: 0, easing: 'easeInOut' } },
    ],
    introPrompts: [
      '함께한 소중한 시간들',
      '새로운 시작을 응원하며',
      '감사와 아쉬움을 담아',
    ],
    outroPrompts: [
      '새로운 곳에서도 빛나세요',
      '항상 응원하겠습니다',
      '또 만날 그날까지',
    ],
  },
  {
    id: 'AWARD_CEREMONY',
    name: '시상식/수상',
    nameEn: 'Award Ceremony',
    icon: '🏆',
    emoji: '🎖️',
    description: '노력의 결실을 축하합니다',
    category: 'business',
    subCategory: 'celebration',
    colors: {
      primary: '#B45309',
      secondary: '#D97706',
      accent: '#FBBF24',
      background: '#FFFBEB',
      text: '#78350F',
      gradient: 'linear-gradient(135deg, #B45309 0%, #FBBF24 100%)',
    },
    fonts: {
      title: 'GmarketSans',
      body: 'Pretendard',
      accent: 'GmarketSans',
    },
    defaultMusic: 'award-triumphant',
    defaultTransition: 'crossDissolve',
    defaultEffect: 'kenburns-zoom-out',
    titleTemplate: '{year} {title} 시상식',
    defaultEnding: '수상을 진심으로 축하합니다! 🏆\n앞으로의 더 큰 성과를 기대합니다 🎖️',
    narrationPrompt: `당신은 시상식/수상 영상의 경축하는 나레이터입니다.
수상의 의미와 노력의 가치를 격려하는 마음으로 전달하세요.
축하하고 격려하는 톤으로 진행하세요.`,
    narrationStyle: 'celebratory, honorable, encouraging',
    suggestedDuration: 90,
    suggestedPhotoCount: { min: 15, max: 40 },
    tags: ['시상식', '수상', '축하', '성과', '노력'],
    premium: false,
    introStyles: [
      { type: 'cinematic', duration: 5, elements: ['title', 'subtitle', 'gradient-bg'], animation: { titleDelay: 1, subtitleDelay: 2.5, easing: 'easeInOut' } },
      { type: 'reveal', duration: 5, elements: ['title', 'logo'], animation: { titleDelay: 0.5, subtitleDelay: 2, easing: 'easeOut' } },
    ],
    outroStyles: [
      { type: 'fireworks', duration: 5, elements: ['message', 'photos'], animation: { messageDelay: 0.5, photosDelay: 2, easing: 'easeOut' } },
      { type: 'confetti', duration: 4, elements: ['message', 'credits'], animation: { messageDelay: 0.5, photosDelay: 1.5, easing: 'easeOut' } },
    ],
    introPrompts: [
      '노력과 열정의 결실',
      '축하의 순간이 시작됩니다',
      '최고의 영예를 드립니다',
    ],
    outroPrompts: [
      '더 큰 성과를 기대합니다',
      '축하합니다, 수고하셨습니다',
      '앞으로의 도전도 응원합니다',
    ],
  },
  {
    id: 'TRAINING_RECAP',
    name: '교육/연수 후기',
    nameEn: 'Training Recap',
    icon: '📚',
    emoji: '🎯',
    description: '배움과 성장의 시간',
    category: 'business',
    subCategory: 'training',
    colors: {
      primary: '#0D9488',
      secondary: '#14B8A6',
      accent: '#2DD4BF',
      background: '#F0FDFA',
      text: '#134E4A',
      gradient: 'linear-gradient(135deg, #0D9488 0%, #2DD4BF 100%)',
    },
    fonts: {
      title: 'Pretendard',
      body: 'Pretendard',
      accent: 'Pretendard',
    },
    defaultMusic: 'learning-inspirational',
    defaultTransition: 'slideRight',
    defaultEffect: 'kenburns-pan-right',
    titleTemplate: '{title} 교육 {year}',
    defaultEnding: '배움의 여정이 계속됩니다! 📚\n오늘의 배움이 내일의 성장으로 🎯',
    narrationPrompt: `당신은 교육/연수 후기 영상의 나레이터입니다.
배움의 가치와 성장의 의미를 전달하세요.
격려하고 영감을 주는 톤으로 진행하세요.`,
    narrationStyle: 'educational, encouraging, growth-oriented',
    suggestedDuration: 90,
    suggestedPhotoCount: { min: 20, max: 50 },
    tags: ['교육', '연수', '학습', '성장', '역량'],
    premium: false,
    introStyles: [
      { type: 'typewriter', duration: 4, elements: ['title', 'subtitle'], animation: { titleDelay: 0, subtitleDelay: 2, easing: 'linear' } },
      { type: 'slide-up', duration: 4, elements: ['title', 'date', 'gradient-bg'], animation: { titleDelay: 0.5, subtitleDelay: 1.5, easing: 'easeOut' } },
    ],
    outroStyles: [
      { type: 'photo-collage', duration: 5, elements: ['message', 'photos', 'credits'], animation: { messageDelay: 0.5, photosDelay: 0, easing: 'easeOut' } },
      { type: 'thank-you', duration: 5, elements: ['message', 'credits'], animation: { messageDelay: 0, photosDelay: 2, easing: 'easeInOut' } },
    ],
    introPrompts: [
      '배움과 성장의 시간',
      '함께 배우고 함께 성장',
      '미래를 준비하는 교육',
    ],
    outroPrompts: [
      '오늘의 배움, 내일의 성장',
      '함께 배워서 더 빛났습니다',
      '계속해서 성장해 나가요',
    ],
  },
  {
    id: 'YEARLY_REVIEW',
    name: '연간 리뷰',
    nameEn: 'Yearly Review',
    icon: '📈',
    emoji: '📊',
    description: '한 해의 성과를 돌아봅니다',
    category: 'business',
    subCategory: 'review',
    colors: {
      primary: '#2563EB',
      secondary: '#3B82F6',
      accent: '#60A5FA',
      background: '#EFF6FF',
      text: '#1E40AF',
      gradient: 'linear-gradient(135deg, #2563EB 0%, #60A5FA 100%)',
    },
    fonts: {
      title: 'Pretendard',
      body: 'Pretendard',
      accent: 'Pretendard',
    },
    defaultMusic: 'corporate-achievement',
    defaultTransition: 'crossDissolve',
    defaultEffect: 'kenburns-pan-right',
    titleTemplate: '{company} {year}년 리뷰',
    defaultEnding: '한 해 동안 수고 많으셨습니다! 📈\n내년에도 함께 성장해요 📊',
    narrationPrompt: `당신은 연간 리뷰 영상의 전문적인 나레이터입니다.
한 해의 성과와 도전, 성장을 의미 있게 전달하세요.
자신감 있고 전문적인 톤으로 진행하세요.`,
    narrationStyle: 'professional, reflective, forward-looking',
    suggestedDuration: 120,
    suggestedPhotoCount: { min: 25, max: 60 },
    tags: ['연간리뷰', '성과', '회고', '성장', '목표'],
    premium: true,
    introStyles: [
      { type: 'cinematic', duration: 5, elements: ['title', 'subtitle', 'logo', 'gradient-bg'], animation: { titleDelay: 1, subtitleDelay: 2.5, easing: 'easeInOut' } },
      { type: 'reveal', duration: 5, elements: ['title', 'date'], animation: { titleDelay: 0.5, subtitleDelay: 2, easing: 'easeOut' } },
    ],
    outroStyles: [
      { type: 'timeline', duration: 6, elements: ['message', 'photos', 'credits'], animation: { messageDelay: 0, photosDelay: 1.5, easing: 'easeInOut' } },
      { type: 'zoom-out', duration: 5, elements: ['message', 'logo'], animation: { messageDelay: 0.5, photosDelay: 2, easing: 'easeOut' } },
    ],
    introPrompts: [
      '한 해를 돌아보며',
      '성과와 도전의 기록',
      '함께 이룬 성장의 발자취',
    ],
    outroPrompts: [
      '내년에도 함께 성장해요',
      '더 큰 도약을 향해',
      '수고하셨습니다, 화이팅',
    ],
  },
  {
    id: 'STARTUP_PITCH',
    name: '스타트업 피치',
    nameEn: 'Startup Pitch',
    icon: '💡',
    emoji: '🚀',
    description: '아이디어로 세상을 바꾸다',
    category: 'business',
    subCategory: 'startup',
    colors: {
      primary: '#EC4899',
      secondary: '#F472B6',
      accent: '#F9A8D4',
      background: '#FDF2F8',
      text: '#9D174D',
      gradient: 'linear-gradient(135deg, #EC4899 0%, #F9A8D4 100%)',
    },
    fonts: {
      title: 'Pretendard',
      body: 'Pretendard',
      accent: 'Pretendard',
    },
    defaultMusic: 'startup-innovative',
    defaultTransition: 'slideLeft',
    defaultEffect: 'kenburns-zoom-in',
    titleTemplate: '{company} 피치덱',
    defaultEnding: '함께 미래를 만들어갑니다! 💡\n새로운 도전에 함께해주세요 🚀',
    narrationPrompt: `당신은 스타트업 피치 영상의 설득력 있는 나레이터입니다.
혁신적인 아이디어와 비전을 열정적으로 전달하세요.
열정적이고 설득력 있는 톤으로 진행하세요.`,
    narrationStyle: 'passionate, innovative, persuasive',
    suggestedDuration: 90,
    suggestedPhotoCount: { min: 15, max: 40 },
    tags: ['스타트업', '피치', '혁신', '창업', '투자'],
    premium: true,
    introStyles: [
      { type: 'explosion', duration: 4, elements: ['title', 'logo', 'gradient-bg'], animation: { titleDelay: 0.3, subtitleDelay: 1.5, easing: 'easeOutBack' } },
      { type: 'dynamic-zoom', duration: 4, elements: ['title', 'subtitle'], animation: { titleDelay: 0.3, subtitleDelay: 1.2, easing: 'easeOut' } },
    ],
    outroStyles: [
      { type: 'fireworks', duration: 5, elements: ['message', 'logo', 'social'], animation: { messageDelay: 0.5, photosDelay: 2, easing: 'easeOut' } },
      { type: 'zoom-out', duration: 4, elements: ['message', 'qrCode'], animation: { messageDelay: 0.5, photosDelay: 2, easing: 'easeOut' } },
    ],
    introPrompts: [
      '세상을 바꿀 아이디어',
      '혁신은 여기서 시작됩니다',
      '미래를 만들어가는 팀',
    ],
    outroPrompts: [
      '함께 미래를 만들어요',
      '새로운 도전에 함께해주세요',
      '투자의 기회를 잡으세요',
    ],
  },
];
