import { Theme } from '@/types/theme';

export const EDUCATION_THEMES: Theme[] = [
  {
    id: 'GRADUATION_ELEMENTARY',
    name: '초등학교 졸업',
    nameEn: 'Elementary Graduation',
    icon: '🎒',
    emoji: '🎓',
    description: '6년간의 소중한 추억을 담아요',
    category: 'education',
    subCategory: 'graduation',
    colors: {
      primary: '#10B981',
      secondary: '#34D399',
      accent: '#6EE7B7',
      background: '#ECFDF5',
      text: '#064E3B',
      gradient: 'linear-gradient(135deg, #10B981 0%, #34D399 100%)',
    },
    fonts: {
      title: 'GmarketSans',
      body: 'Pretendard',
      accent: 'GmarketSans',
    },
    defaultMusic: 'graduation-cheerful',
    defaultTransition: 'fade',
    defaultEffect: 'kenburns-zoom-in',
    titleTemplate: '{name}의 초등학교 졸업',
    defaultEnding: '초등학교 졸업을 축하해요!\n중학교에서도 화이팅! 🎉',
    narrationPrompt: `당신은 따뜻하고 격려하는 초등학교 졸업 영상 나레이터입니다.
아이들이 이해할 수 있는 쉬운 말로, 6년간의 성장과 추억을 감동적으로 전달하세요.
친구들과의 우정, 선생님에 대한 감사, 새로운 시작에 대한 기대를 담아주세요.
밝고 희망찬 톤으로 진행하되, 가끔 유머를 넣어 재미있게 만들어주세요.`,
    narrationStyle: 'warm, encouraging, child-friendly',
    suggestedDuration: 90,
    suggestedPhotoCount: { min: 15, max: 40 },
    tags: ['졸업', '초등학교', '성장', '추억', '아이들'],
    premium: false,
    introStyles: [
      { type: 'bounce', duration: 5, elements: ['title', 'subtitle', 'particles'], animation: { titleDelay: 0.5, subtitleDelay: 1.5, easing: 'easeOutBounce' } },
      { type: 'typewriter', duration: 5, elements: ['title', 'date', 'gradient-bg'], animation: { titleDelay: 0, subtitleDelay: 2, easing: 'linear' } },
    ],
    outroStyles: [
      { type: 'confetti', duration: 5, elements: ['message', 'photos'], animation: { messageDelay: 0.5, photosDelay: 2, easing: 'easeOut' } },
      { type: 'balloon', duration: 5, elements: ['message', 'credits'], animation: { messageDelay: 0, photosDelay: 1.5, easing: 'easeOutBack' } },
    ],
    introPrompts: [
      '밝고 신나는 분위기로, 초등학교 졸업의 기쁨을 표현',
      '6년간의 여정을 시작하며, 설렘과 기대감을 담아',
      '무지개처럼 다채로운 추억들이 펼쳐질 준비',
    ],
    outroPrompts: [
      '새로운 시작을 향한 희망찬 메시지',
      '친구들과의 우정이 영원하길 바라며',
      '선생님과 부모님께 감사의 마음을 전하며',
    ],
  },
  {
    id: 'GRADUATION_MIDDLE',
    name: '중학교 졸업',
    nameEn: 'Middle School Graduation',
    icon: '📚',
    emoji: '🎓',
    description: '청소년기의 성장과 도전을 담아요',
    category: 'education',
    subCategory: 'graduation',
    colors: {
      primary: '#3B82F6',
      secondary: '#60A5FA',
      accent: '#93C5FD',
      background: '#EFF6FF',
      text: '#1E3A8A',
      gradient: 'linear-gradient(135deg, #3B82F6 0%, #60A5FA 100%)',
    },
    fonts: {
      title: 'Pretendard',
      body: 'Pretendard',
      accent: 'GmarketSans',
    },
    defaultMusic: 'graduation-emotional',
    defaultTransition: 'crossDissolve',
    defaultEffect: 'kenburns-pan-right',
    titleTemplate: '{name}의 중학교 졸업',
    defaultEnding: '중학교 3년, 정말 수고했어!\n고등학교에서 더 멋진 너를 응원할게! 💪',
    narrationPrompt: `당신은 중학교 졸업 영상의 나레이터입니다.
청소년기의 성장, 도전, 우정을 진솔하게 담아주세요.
사춘기의 방황과 성장, 친구들과의 추억, 미래에 대한 기대를 표현하세요.
감동적이면서도 희망적인 메시지를 전달해주세요.`,
    narrationStyle: 'sincere, encouraging, youthful',
    suggestedDuration: 120,
    suggestedPhotoCount: { min: 20, max: 50 },
    tags: ['졸업', '중학교', '청소년', '성장', '도전'],
    premium: false,
    introStyles: [
      { type: 'cinematic', duration: 5, elements: ['title', 'subtitle', 'gradient-bg'], animation: { titleDelay: 1, subtitleDelay: 2.5, easing: 'easeInOut' } },
      { type: 'slide-up', duration: 4, elements: ['title', 'date'], animation: { titleDelay: 0.5, subtitleDelay: 1.5, easing: 'easeOut' } },
    ],
    outroStyles: [
      { type: 'scroll-credits', duration: 6, elements: ['message', 'credits', 'photos'], animation: { messageDelay: 0, photosDelay: 2, easing: 'linear' } },
      { type: 'photo-collage', duration: 5, elements: ['message', 'photos'], animation: { messageDelay: 1, photosDelay: 0, easing: 'easeOut' } },
    ],
    introPrompts: [
      '청소년기의 열정과 도전 정신을 담아',
      '3년간의 성장 여정이 시작됩니다',
      '우정과 추억이 가득한 이야기',
    ],
    outroPrompts: [
      '더 넓은 세상으로 나아가는 첫 걸음',
      '함께한 친구들에게 고마움을 전하며',
      '새로운 도전을 향해 힘차게',
    ],
  },
  {
    id: 'GRADUATION_HIGH',
    name: '고등학교 졸업',
    nameEn: 'High School Graduation',
    icon: '🏫',
    emoji: '🎓',
    description: '치열했던 3년, 그리고 새로운 시작',
    category: 'education',
    subCategory: 'graduation',
    colors: {
      primary: '#8B5CF6',
      secondary: '#A78BFA',
      accent: '#C4B5FD',
      background: '#F5F3FF',
      text: '#4C1D95',
      gradient: 'linear-gradient(135deg, #8B5CF6 0%, #A78BFA 100%)',
    },
    fonts: {
      title: 'Pretendard',
      body: 'Pretendard',
      accent: 'GmarketSans',
    },
    defaultMusic: 'graduation-epic',
    defaultTransition: 'crossDissolve',
    defaultEffect: 'kenburns-zoom-out',
    titleTemplate: '{name}의 고등학교 졸업',
    defaultEnding: '고등학교 졸업을 진심으로 축하해!\n꿈을 향해 나아가는 너를 응원할게! 🌟',
    narrationPrompt: `당신은 고등학교 졸업 영상의 나레이터입니다.
치열했던 입시 준비, 친구들과의 우정, 청춘의 열정을 담아주세요.
힘들었던 순간들을 이겨낸 성취감과 새로운 시작에 대한 기대를 표현하세요.
감동적이고 성숙한 톤으로 진행해주세요.`,
    narrationStyle: 'mature, emotional, hopeful',
    suggestedDuration: 150,
    suggestedPhotoCount: { min: 25, max: 60 },
    tags: ['졸업', '고등학교', '청춘', '꿈', '미래'],
    premium: false,
    introStyles: [
      { type: 'cinematic', duration: 6, elements: ['title', 'subtitle', 'gradient-bg'], animation: { titleDelay: 1.5, subtitleDelay: 3, easing: 'easeInOutCubic' } },
      { type: 'elegant-fade', duration: 5, elements: ['title', 'date', 'particles'], animation: { titleDelay: 1, subtitleDelay: 2.5, easing: 'easeOut' } },
    ],
    outroStyles: [
      { type: 'timeline', duration: 7, elements: ['message', 'photos', 'credits'], animation: { messageDelay: 0, photosDelay: 1.5, easing: 'easeInOut' } },
      { type: 'fireworks', duration: 5, elements: ['message', 'photos'], animation: { messageDelay: 0.5, photosDelay: 2, easing: 'easeOut' } },
    ],
    introPrompts: [
      '청춘의 열정과 도전이 담긴 3년',
      '꿈을 향해 달려온 시간들',
      '함께여서 더 빛났던 순간들',
    ],
    outroPrompts: [
      '새로운 세계로 나아가는 문 앞에서',
      '영원히 기억될 우리의 청춘',
      '각자의 길에서 다시 만날 그날까지',
    ],
  },
  {
    id: 'GRADUATION_UNIVERSITY',
    name: '대학교 졸업',
    nameEn: 'University Graduation',
    icon: '🎓',
    emoji: '🎉',
    description: '학문의 전당을 떠나 세상으로',
    category: 'education',
    subCategory: 'graduation',
    colors: {
      primary: '#DC2626',
      secondary: '#EF4444',
      accent: '#FCA5A5',
      background: '#FEF2F2',
      text: '#7F1D1D',
      gradient: 'linear-gradient(135deg, #DC2626 0%, #EF4444 100%)',
    },
    fonts: {
      title: 'Pretendard',
      body: 'Pretendard',
      accent: 'GmarketSans',
    },
    defaultMusic: 'graduation-triumphant',
    defaultTransition: 'crossDissolve',
    defaultEffect: 'kenburns-diagonal-tr',
    titleTemplate: '{name}의 대학교 졸업',
    defaultEnding: '대학 졸업을 축하합니다!\n세상을 향해 힘차게 나아가세요! 🎓✨',
    narrationPrompt: `당신은 대학교 졸업 영상의 나레이터입니다.
학문적 성취, 캠퍼스 라이프, 동아리와 친구들과의 추억을 담아주세요.
사회로 나아가는 새로운 시작에 대한 기대와 각오를 표현하세요.
성숙하고 당당한 톤으로 진행해주세요.`,
    narrationStyle: 'professional, confident, celebratory',
    suggestedDuration: 180,
    suggestedPhotoCount: { min: 30, max: 80 },
    tags: ['졸업', '대학교', '학사', '취업', '미래'],
    premium: true,
    introStyles: [
      { type: 'cinematic', duration: 6, elements: ['title', 'subtitle', 'logo', 'gradient-bg'], animation: { titleDelay: 1.5, subtitleDelay: 3.5, easing: 'easeInOutQuart' } },
      { type: 'reveal', duration: 5, elements: ['title', 'date'], animation: { titleDelay: 0.5, subtitleDelay: 2, easing: 'easeOut' } },
    ],
    outroStyles: [
      { type: 'scroll-credits', duration: 8, elements: ['message', 'credits', 'photos', 'logo'], animation: { messageDelay: 0, photosDelay: 2, easing: 'linear' } },
      { type: 'photo-collage', duration: 6, elements: ['message', 'photos'], animation: { messageDelay: 1, photosDelay: 0, easing: 'easeOut' } },
    ],
    introPrompts: [
      '학문의 전당에서 보낸 소중한 시간',
      '꿈을 키우고 성장한 캠퍼스 라이프',
      '이제 세상이라는 무대로',
    ],
    outroPrompts: [
      '새로운 도전이 시작되는 순간',
      '함께한 모든 이들에게 감사를',
      '세상을 빛낼 당신의 미래를 응원합니다',
    ],
  },
  {
    id: 'SCHOOL_FESTIVAL',
    name: '학교 축제',
    nameEn: 'School Festival',
    icon: '🎪',
    emoji: '🎊',
    description: '신나는 축제의 순간들',
    category: 'education',
    subCategory: 'event',
    colors: {
      primary: '#F59E0B',
      secondary: '#FBBF24',
      accent: '#FCD34D',
      background: '#FFFBEB',
      text: '#78350F',
      gradient: 'linear-gradient(135deg, #F59E0B 0%, #FBBF24 100%)',
    },
    fonts: {
      title: 'GmarketSans',
      body: 'Pretendard',
      accent: 'GmarketSans',
    },
    defaultMusic: 'festival-upbeat',
    defaultTransition: 'slideRight',
    defaultEffect: 'kenburns-zoom-in',
    titleTemplate: '{year} {school} 축제',
    defaultEnding: '즐거웠던 축제의 순간들!\n내년에 또 만나요! 🎪🎉',
    narrationPrompt: `당신은 학교 축제 영상의 활기찬 나레이터입니다.
축제의 신나는 분위기, 다양한 공연과 부스, 친구들과의 즐거운 시간을 생동감 있게 전달하세요.
밝고 에너지 넘치는 톤으로 진행하세요.`,
    narrationStyle: 'energetic, fun, lively',
    suggestedDuration: 90,
    suggestedPhotoCount: { min: 20, max: 50 },
    tags: ['축제', '학교', '공연', '부스', '친구'],
    premium: false,
    introStyles: [
      { type: 'explosion', duration: 4, elements: ['title', 'particles', 'gradient-bg'], animation: { titleDelay: 0.3, subtitleDelay: 1.5, easing: 'easeOutBack' } },
      { type: 'bounce', duration: 4, elements: ['title', 'date'], animation: { titleDelay: 0.5, subtitleDelay: 1.5, easing: 'easeOutBounce' } },
    ],
    outroStyles: [
      { type: 'confetti', duration: 4, elements: ['message', 'photos'], animation: { messageDelay: 0.5, photosDelay: 1.5, easing: 'easeOut' } },
      { type: 'fireworks', duration: 5, elements: ['message', 'photos'], animation: { messageDelay: 0, photosDelay: 2, easing: 'easeOut' } },
    ],
    introPrompts: [
      '축제의 열기가 가득한 순간',
      '모두가 하나되어 즐기는 우리 축제',
      '잊지 못할 추억이 시작됩니다',
    ],
    outroPrompts: [
      '함께해서 더 즐거웠던 축제',
      '내년에 더 신나게 만나요',
      '축제의 여운이 가득한 추억',
    ],
  },
  {
    id: 'SPORTS_DAY',
    name: '운동회/체육대회',
    nameEn: 'Sports Day',
    icon: '🏃',
    emoji: '🏆',
    description: '땀과 열정이 빛나는 순간',
    category: 'education',
    subCategory: 'event',
    colors: {
      primary: '#059669',
      secondary: '#10B981',
      accent: '#34D399',
      background: '#ECFDF5',
      text: '#064E3B',
      gradient: 'linear-gradient(135deg, #059669 0%, #10B981 100%)',
    },
    fonts: {
      title: 'GmarketSans',
      body: 'Pretendard',
      accent: 'GmarketSans',
    },
    defaultMusic: 'sports-dynamic',
    defaultTransition: 'slideLeft',
    defaultEffect: 'kenburns-pan-left',
    titleTemplate: '{year} {school} 체육대회',
    defaultEnding: '모두가 승리자입니다!\n열정을 보여준 모든 선수들 화이팅! 🏆',
    narrationPrompt: `당신은 운동회/체육대회 영상의 역동적인 나레이터입니다.
경기의 긴장감, 응원의 열기, 승리의 기쁨과 노력의 가치를 전달하세요.
역동적이고 열정적인 톤으로 진행하세요.`,
    narrationStyle: 'dynamic, exciting, passionate',
    suggestedDuration: 120,
    suggestedPhotoCount: { min: 25, max: 60 },
    tags: ['운동회', '체육대회', '스포츠', '열정', '팀워크'],
    premium: false,
    introStyles: [
      { type: 'dynamic-zoom', duration: 4, elements: ['title', 'subtitle', 'gradient-bg'], animation: { titleDelay: 0.3, subtitleDelay: 1.2, easing: 'easeOutExpo' } },
      { type: 'split', duration: 4, elements: ['title', 'date'], animation: { titleDelay: 0.5, subtitleDelay: 1.5, easing: 'easeOut' } },
    ],
    outroStyles: [
      { type: 'photo-collage', duration: 5, elements: ['message', 'photos'], animation: { messageDelay: 0.5, photosDelay: 0, easing: 'easeOut' } },
      { type: 'fireworks', duration: 4, elements: ['message', 'credits'], animation: { messageDelay: 0.5, photosDelay: 2, easing: 'easeOut' } },
    ],
    introPrompts: [
      '열정과 도전의 무대',
      '최선을 다하는 모든 순간',
      '함께 뛰고, 함께 응원하고',
    ],
    outroPrompts: [
      '땀과 노력이 빛나는 순간',
      '모두가 승리자인 오늘',
      '내년에 더 강해져서 만나요',
    ],
  },
  {
    id: 'FIELD_TRIP',
    name: '수학여행/현장학습',
    nameEn: 'Field Trip',
    icon: '🚌',
    emoji: '✈️',
    description: '함께 떠난 특별한 여행',
    category: 'education',
    subCategory: 'event',
    colors: {
      primary: '#0EA5E9',
      secondary: '#38BDF8',
      accent: '#7DD3FC',
      background: '#F0F9FF',
      text: '#0C4A6E',
      gradient: 'linear-gradient(135deg, #0EA5E9 0%, #38BDF8 100%)',
    },
    fonts: {
      title: 'GmarketSans',
      body: 'Pretendard',
      accent: 'GmarketSans',
    },
    defaultMusic: 'travel-adventure',
    defaultTransition: 'slideUp',
    defaultEffect: 'kenburns-pan-right',
    titleTemplate: '{destination} 수학여행',
    defaultEnding: '함께여서 더 즐거웠던 여행!\n추억을 가슴에 담고 돌아갑니다 🚌✨',
    narrationPrompt: `당신은 수학여행/현장학습 영상의 나레이터입니다.
새로운 곳에서의 발견, 친구들과의 추억, 즐거운 순간들을 생동감 있게 전달하세요.
밝고 설레는 톤으로 진행하세요.`,
    narrationStyle: 'adventurous, cheerful, memorable',
    suggestedDuration: 120,
    suggestedPhotoCount: { min: 30, max: 70 },
    tags: ['수학여행', '현장학습', '여행', '추억', '친구'],
    premium: false,
    introStyles: [
      { type: 'slide-up', duration: 4, elements: ['title', 'subtitle', 'gradient-bg'], animation: { titleDelay: 0.5, subtitleDelay: 1.5, easing: 'easeOut' } },
      { type: 'photo-stack', duration: 5, elements: ['title', 'date', 'particles'], animation: { titleDelay: 1, subtitleDelay: 2.5, easing: 'easeOutBack' } },
    ],
    outroStyles: [
      { type: 'flying-photos', duration: 5, elements: ['message', 'photos'], animation: { messageDelay: 0.5, photosDelay: 0, easing: 'easeInOut' } },
      { type: 'memories', duration: 6, elements: ['message', 'photos', 'credits'], animation: { messageDelay: 0, photosDelay: 1.5, easing: 'easeOut' } },
    ],
    introPrompts: [
      '설레는 마음으로 떠나는 여행',
      '새로운 곳에서 만나는 특별한 추억',
      '함께라서 더 즐거운 모험',
    ],
    outroPrompts: [
      '평생 간직할 소중한 추억',
      '함께한 모든 순간에 감사를',
      '다음 여행을 기약하며',
    ],
  },
  {
    id: 'CLASS_MEMORY',
    name: '우리 반 추억',
    nameEn: 'Class Memories',
    icon: '👨‍👩‍👧‍👦',
    emoji: '💝',
    description: '한 해 동안 함께한 추억',
    category: 'education',
    subCategory: 'class',
    colors: {
      primary: '#EC4899',
      secondary: '#F472B6',
      accent: '#F9A8D4',
      background: '#FDF2F8',
      text: '#831843',
      gradient: 'linear-gradient(135deg, #EC4899 0%, #F472B6 100%)',
    },
    fonts: {
      title: 'GmarketSans',
      body: 'Pretendard',
      accent: 'GmarketSans',
    },
    defaultMusic: 'friendship-warm',
    defaultTransition: 'crossDissolve',
    defaultEffect: 'kenburns-zoom-in',
    titleTemplate: '{year}년 {class} 추억',
    defaultEnding: '우리 반 최고!\n영원히 기억할 소중한 친구들 💕',
    narrationPrompt: `당신은 학급 추억 영상의 따뜻한 나레이터입니다.
한 해 동안 함께한 반 친구들과의 소중한 순간들을 담아주세요.
따뜻하고 정감 있는 톤으로 진행하세요.`,
    narrationStyle: 'warm, friendly, nostalgic',
    suggestedDuration: 90,
    suggestedPhotoCount: { min: 20, max: 50 },
    tags: ['우리반', '학급', '친구', '추억', '1년'],
    premium: false,
    introStyles: [
      { type: 'floating', duration: 4, elements: ['title', 'subtitle', 'particles'], animation: { titleDelay: 0.5, subtitleDelay: 1.5, easing: 'easeOutSine' } },
      { type: 'typewriter', duration: 4, elements: ['title', 'date'], animation: { titleDelay: 0, subtitleDelay: 2, easing: 'linear' } },
    ],
    outroStyles: [
      { type: 'heart-gather', duration: 5, elements: ['message', 'photos'], animation: { messageDelay: 0.5, photosDelay: 1, easing: 'easeOut' } },
      { type: 'polaroid-stack', duration: 5, elements: ['message', 'photos', 'credits'], animation: { messageDelay: 0, photosDelay: 1.5, easing: 'easeOutBack' } },
    ],
    introPrompts: [
      '함께여서 행복했던 우리 반',
      '웃음과 눈물이 함께한 1년',
      '영원히 기억될 우리들의 이야기',
    ],
    outroPrompts: [
      '헤어져도 마음은 함께',
      '우리 반 영원히 최고',
      '다시 만날 그날까지',
    ],
  },
  {
    id: 'TEACHER_APPRECIATION',
    name: '스승의 날/선생님 감사',
    nameEn: 'Teacher Appreciation',
    icon: '👩‍🏫',
    emoji: '🌷',
    description: '선생님께 전하는 감사의 마음',
    category: 'education',
    subCategory: 'appreciation',
    colors: {
      primary: '#D946EF',
      secondary: '#E879F9',
      accent: '#F0ABFC',
      background: '#FDF4FF',
      text: '#701A75',
      gradient: 'linear-gradient(135deg, #D946EF 0%, #E879F9 100%)',
    },
    fonts: {
      title: 'GmarketSans',
      body: 'Pretendard',
      accent: 'GmarketSans',
    },
    defaultMusic: 'appreciation-heartfelt',
    defaultTransition: 'fade',
    defaultEffect: 'kenburns-zoom-in',
    titleTemplate: '사랑하는 {teacher} 선생님께',
    defaultEnding: '선생님, 감사합니다.\n선생님의 가르침을 평생 간직하겠습니다 🌷',
    narrationPrompt: `당신은 스승의 날 감사 영상의 진심 어린 나레이터입니다.
선생님께 대한 감사와 존경의 마음을 정성껏 전달해주세요.
진심 어리고 감동적인 톤으로 진행하세요.`,
    narrationStyle: 'respectful, grateful, heartfelt',
    suggestedDuration: 60,
    suggestedPhotoCount: { min: 10, max: 30 },
    tags: ['스승의날', '선생님', '감사', '존경', '교육'],
    premium: false,
    introStyles: [
      { type: 'elegant-fade', duration: 5, elements: ['title', 'subtitle', 'gradient-bg'], animation: { titleDelay: 1, subtitleDelay: 2.5, easing: 'easeInOut' } },
      { type: 'floating', duration: 4, elements: ['title', 'particles'], animation: { titleDelay: 0.5, subtitleDelay: 1.5, easing: 'easeOut' } },
    ],
    outroStyles: [
      { type: 'flower-bloom', duration: 5, elements: ['message', 'photos'], animation: { messageDelay: 0.5, photosDelay: 2, easing: 'easeOut' } },
      { type: 'thank-you', duration: 5, elements: ['message', 'credits'], animation: { messageDelay: 0, photosDelay: 2, easing: 'easeInOut' } },
    ],
    introPrompts: [
      '감사의 마음을 담아',
      '선생님께 드리는 작은 선물',
      '가르침에 대한 진심 어린 감사',
    ],
    outroPrompts: [
      '선생님의 은혜를 잊지 않겠습니다',
      '항상 건강하시고 행복하세요',
      '사랑합니다, 선생님',
    ],
  },
  {
    id: 'CLUB_ACTIVITY',
    name: '동아리 활동',
    nameEn: 'Club Activity',
    icon: '🎸',
    emoji: '🎯',
    description: '열정을 함께한 동아리 추억',
    category: 'education',
    subCategory: 'club',
    colors: {
      primary: '#6366F1',
      secondary: '#818CF8',
      accent: '#A5B4FC',
      background: '#EEF2FF',
      text: '#3730A3',
      gradient: 'linear-gradient(135deg, #6366F1 0%, #818CF8 100%)',
    },
    fonts: {
      title: 'GmarketSans',
      body: 'Pretendard',
      accent: 'GmarketSans',
    },
    defaultMusic: 'club-energetic',
    defaultTransition: 'slideLeft',
    defaultEffect: 'kenburns-pan-left',
    titleTemplate: '{club} 동아리 활동기록',
    defaultEnding: '함께한 열정, 함께 성장한 시간!\n우리 동아리 화이팅! 💪',
    narrationPrompt: `당신은 동아리 활동 영상의 나레이터입니다.
동아리에서의 열정적인 활동, 성장, 팀워크를 생동감 있게 전달하세요.
활기차고 열정적인 톤으로 진행하세요.`,
    narrationStyle: 'passionate, energetic, team-spirited',
    suggestedDuration: 90,
    suggestedPhotoCount: { min: 20, max: 50 },
    tags: ['동아리', '활동', '열정', '팀워크', '성장'],
    premium: false,
    introStyles: [
      { type: 'dynamic-zoom', duration: 4, elements: ['title', 'subtitle', 'gradient-bg'], animation: { titleDelay: 0.3, subtitleDelay: 1.2, easing: 'easeOut' } },
      { type: 'split', duration: 4, elements: ['title', 'logo'], animation: { titleDelay: 0.5, subtitleDelay: 1.5, easing: 'easeOutBack' } },
    ],
    outroStyles: [
      { type: 'photo-collage', duration: 5, elements: ['message', 'photos', 'credits'], animation: { messageDelay: 0.5, photosDelay: 0, easing: 'easeOut' } },
      { type: 'fireworks', duration: 4, elements: ['message'], animation: { messageDelay: 0.5, photosDelay: 2, easing: 'easeOut' } },
    ],
    introPrompts: [
      '열정으로 가득한 우리 동아리',
      '함께 성장하는 즐거움',
      '꿈을 향해 달려가는 우리들',
    ],
    outroPrompts: [
      '함께해서 더 빛났던 시간',
      '앞으로도 계속될 우리의 열정',
      '동아리 영원히 화이팅',
    ],
  },
  {
    id: 'SCHOOL_PLAY',
    name: '학예회/발표회',
    nameEn: 'School Play',
    icon: '🎭',
    emoji: '🎬',
    description: '무대 위의 빛나는 순간',
    category: 'education',
    subCategory: 'performance',
    colors: {
      primary: '#BE185D',
      secondary: '#DB2777',
      accent: '#F472B6',
      background: '#FDF2F8',
      text: '#831843',
      gradient: 'linear-gradient(135deg, #BE185D 0%, #DB2777 100%)',
    },
    fonts: {
      title: 'GmarketSans',
      body: 'Pretendard',
      accent: 'GmarketSans',
    },
    defaultMusic: 'performance-dramatic',
    defaultTransition: 'crossDissolve',
    defaultEffect: 'kenburns-zoom-out',
    titleTemplate: '{year} {title} 발표회',
    defaultEnding: '무대 위에서 빛난 모든 순간!\n최고의 공연이었습니다 👏',
    narrationPrompt: `당신은 학예회/발표회 영상의 드라마틱한 나레이터입니다.
무대 위의 긴장감, 노력의 결실, 감동의 순간을 전달하세요.
드라마틱하면서도 따뜻한 톤으로 진행하세요.`,
    narrationStyle: 'dramatic, celebratory, proud',
    suggestedDuration: 120,
    suggestedPhotoCount: { min: 20, max: 50 },
    tags: ['학예회', '발표회', '공연', '무대', '연극'],
    premium: false,
    introStyles: [
      { type: 'curtain', duration: 5, elements: ['title', 'subtitle', 'gradient-bg'], animation: { titleDelay: 1.5, subtitleDelay: 3, easing: 'easeInOut' } },
      { type: 'cinematic', duration: 5, elements: ['title', 'date'], animation: { titleDelay: 1, subtitleDelay: 2.5, easing: 'easeInOutQuart' } },
    ],
    outroStyles: [
      { type: 'scroll-credits', duration: 6, elements: ['message', 'credits', 'photos'], animation: { messageDelay: 0, photosDelay: 2, easing: 'linear' } },
      { type: 'fireworks', duration: 5, elements: ['message', 'photos'], animation: { messageDelay: 0.5, photosDelay: 2, easing: 'easeOut' } },
    ],
    introPrompts: [
      '막이 오르기 전의 설렘',
      '무대를 빛낼 우리들의 순간',
      '땀과 노력이 만든 작품',
    ],
    outroPrompts: [
      '최고의 박수를 받을 자격이 있는',
      '무대 위의 모든 순간이 빛났습니다',
      '다음 무대에서 또 만나요',
    ],
  },
  {
    id: 'ENTRANCE_CEREMONY',
    name: '입학식',
    nameEn: 'Entrance Ceremony',
    icon: '🌸',
    emoji: '📖',
    description: '새로운 시작을 축하해요',
    category: 'education',
    subCategory: 'ceremony',
    colors: {
      primary: '#F472B6',
      secondary: '#FB7185',
      accent: '#FDA4AF',
      background: '#FFF1F2',
      text: '#9F1239',
      gradient: 'linear-gradient(135deg, #F472B6 0%, #FB7185 100%)',
    },
    fonts: {
      title: 'GmarketSans',
      body: 'Pretendard',
      accent: 'GmarketSans',
    },
    defaultMusic: 'new-beginning',
    defaultTransition: 'fade',
    defaultEffect: 'kenburns-zoom-in',
    titleTemplate: '{name}의 입학을 축하해요!',
    defaultEnding: '새로운 시작을 축하합니다!\n멋진 학교생활이 되길 바랍니다 🌸',
    narrationPrompt: `당신은 입학식 영상의 희망찬 나레이터입니다.
새로운 시작에 대한 설렘과 기대를 담아주세요.
밝고 희망찬 톤으로 진행하세요.`,
    narrationStyle: 'hopeful, cheerful, welcoming',
    suggestedDuration: 60,
    suggestedPhotoCount: { min: 10, max: 25 },
    tags: ['입학식', '새출발', '시작', '희망', '학교'],
    premium: false,
    introStyles: [
      { type: 'fade-zoom', duration: 4, elements: ['title', 'subtitle', 'particles'], animation: { titleDelay: 0.5, subtitleDelay: 1.5, easing: 'easeOut' } },
      { type: 'floating', duration: 4, elements: ['title', 'date', 'gradient-bg'], animation: { titleDelay: 0.5, subtitleDelay: 1.5, easing: 'easeOutSine' } },
    ],
    outroStyles: [
      { type: 'flower-bloom', duration: 4, elements: ['message', 'photos'], animation: { messageDelay: 0.5, photosDelay: 2, easing: 'easeOut' } },
      { type: 'confetti', duration: 4, elements: ['message'], animation: { messageDelay: 0.5, photosDelay: 2, easing: 'easeOut' } },
    ],
    introPrompts: [
      '새로운 시작의 첫 페이지',
      '설렘 가득한 첫 걸음',
      '희망찬 미래가 시작됩니다',
    ],
    outroPrompts: [
      '멋진 학교생활이 되길',
      '꿈을 향해 한 걸음씩',
      '새로운 친구들과 함께',
    ],
  },
  {
    id: 'STUDY_GROUP',
    name: '스터디/프로젝트 팀',
    nameEn: 'Study Group',
    icon: '📖',
    emoji: '💡',
    description: '함께 공부하고 성장한 시간',
    category: 'education',
    subCategory: 'study',
    colors: {
      primary: '#2563EB',
      secondary: '#3B82F6',
      accent: '#60A5FA',
      background: '#EFF6FF',
      text: '#1E40AF',
      gradient: 'linear-gradient(135deg, #2563EB 0%, #3B82F6 100%)',
    },
    fonts: {
      title: 'Pretendard',
      body: 'Pretendard',
      accent: 'GmarketSans',
    },
    defaultMusic: 'study-focus',
    defaultTransition: 'crossDissolve',
    defaultEffect: 'kenburns-pan-right',
    titleTemplate: '{name} 스터디 기록',
    defaultEnding: '함께 공부한 시간이 빛나는 결실로!\n모두 수고했습니다 📚',
    narrationPrompt: `당신은 스터디/프로젝트 팀 영상의 나레이터입니다.
함께 공부하고 성장한 과정을 진솔하게 담아주세요.
진지하면서도 따뜻한 톤으로 진행하세요.`,
    narrationStyle: 'focused, supportive, achievement-oriented',
    suggestedDuration: 60,
    suggestedPhotoCount: { min: 10, max: 30 },
    tags: ['스터디', '프로젝트', '공부', '팀워크', '성장'],
    premium: false,
    introStyles: [
      { type: 'typewriter', duration: 4, elements: ['title', 'subtitle'], animation: { titleDelay: 0, subtitleDelay: 2, easing: 'linear' } },
      { type: 'slide-up', duration: 4, elements: ['title', 'date', 'gradient-bg'], animation: { titleDelay: 0.5, subtitleDelay: 1.5, easing: 'easeOut' } },
    ],
    outroStyles: [
      { type: 'photo-collage', duration: 5, elements: ['message', 'photos', 'credits'], animation: { messageDelay: 0.5, photosDelay: 0, easing: 'easeOut' } },
      { type: 'thank-you', duration: 4, elements: ['message', 'credits'], animation: { messageDelay: 0, photosDelay: 2, easing: 'easeInOut' } },
    ],
    introPrompts: [
      '함께 성장한 시간들',
      '열정으로 가득한 스터디',
      '목표를 향해 달려온 우리',
    ],
    outroPrompts: [
      '노력은 결실을 맺습니다',
      '함께해서 더 빛나는 성과',
      '앞으로도 함께 성장해요',
    ],
  },
  {
    id: 'SCIENCE_FAIR',
    name: '과학전람회/발명대회',
    nameEn: 'Science Fair',
    icon: '🔬',
    emoji: '🧪',
    description: '탐구하고 발견하는 즐거움',
    category: 'education',
    subCategory: 'competition',
    colors: {
      primary: '#0D9488',
      secondary: '#14B8A6',
      accent: '#2DD4BF',
      background: '#F0FDFA',
      text: '#134E4A',
      gradient: 'linear-gradient(135deg, #0D9488 0%, #14B8A6 100%)',
    },
    fonts: {
      title: 'Pretendard',
      body: 'Pretendard',
      accent: 'GmarketSans',
    },
    defaultMusic: 'discovery-wonder',
    defaultTransition: 'slideRight',
    defaultEffect: 'kenburns-zoom-in',
    titleTemplate: '{year} {title} 대회',
    defaultEnding: '탐구하는 열정이 세상을 바꿉니다!\n미래의 과학자들을 응원합니다 🔬',
    narrationPrompt: `당신은 과학전람회/발명대회 영상의 나레이터입니다.
탐구 정신, 창의적 아이디어, 발견의 기쁨을 전달하세요.
호기심 가득하고 지적인 톤으로 진행하세요.`,
    narrationStyle: 'curious, innovative, inspiring',
    suggestedDuration: 90,
    suggestedPhotoCount: { min: 15, max: 40 },
    tags: ['과학', '발명', '탐구', '대회', '창의'],
    premium: false,
    introStyles: [
      { type: 'reveal', duration: 4, elements: ['title', 'subtitle', 'gradient-bg'], animation: { titleDelay: 0.5, subtitleDelay: 2, easing: 'easeOut' } },
      { type: 'glitch', duration: 4, elements: ['title', 'particles'], animation: { titleDelay: 0.3, subtitleDelay: 1.5, easing: 'easeOutExpo' } },
    ],
    outroStyles: [
      { type: 'fireworks', duration: 5, elements: ['message', 'photos'], animation: { messageDelay: 0.5, photosDelay: 2, easing: 'easeOut' } },
      { type: 'photo-collage', duration: 5, elements: ['message', 'photos', 'credits'], animation: { messageDelay: 0.5, photosDelay: 0, easing: 'easeOut' } },
    ],
    introPrompts: [
      '호기심이 세상을 바꾸는 순간',
      '탐구 정신의 빛나는 결실',
      '창의력으로 미래를 설계하다',
    ],
    outroPrompts: [
      '오늘의 발견이 내일의 혁신',
      '끊임없이 질문하고 탐구하라',
      '미래의 과학자들을 응원합니다',
    ],
  },
  {
    id: 'MUSIC_RECITAL',
    name: '음악회/연주회',
    nameEn: 'Music Recital',
    icon: '🎹',
    emoji: '🎵',
    description: '아름다운 선율의 순간',
    category: 'education',
    subCategory: 'performance',
    colors: {
      primary: '#7C3AED',
      secondary: '#8B5CF6',
      accent: '#A78BFA',
      background: '#F5F3FF',
      text: '#5B21B6',
      gradient: 'linear-gradient(135deg, #7C3AED 0%, #8B5CF6 100%)',
    },
    fonts: {
      title: 'GmarketSans',
      body: 'Pretendard',
      accent: 'GmarketSans',
    },
    defaultMusic: 'classical-elegant',
    defaultTransition: 'crossDissolve',
    defaultEffect: 'kenburns-zoom-out',
    titleTemplate: '{title} 연주회',
    defaultEnding: '아름다운 선율에 감사드립니다.\n음악과 함께하는 모든 순간이 행복입니다 🎵',
    narrationPrompt: `당신은 음악회/연주회 영상의 우아한 나레이터입니다.
음악의 아름다움, 연주자의 열정, 감동의 순간을 전달하세요.
우아하고 감성적인 톤으로 진행하세요.`,
    narrationStyle: 'elegant, artistic, emotional',
    suggestedDuration: 120,
    suggestedPhotoCount: { min: 20, max: 50 },
    tags: ['음악회', '연주회', '음악', '클래식', '공연'],
    premium: true,
    introStyles: [
      { type: 'elegant-fade', duration: 5, elements: ['title', 'subtitle', 'gradient-bg'], animation: { titleDelay: 1, subtitleDelay: 2.5, easing: 'easeInOut' } },
      { type: 'curtain', duration: 5, elements: ['title', 'date'], animation: { titleDelay: 1.5, subtitleDelay: 3, easing: 'easeInOutQuart' } },
    ],
    outroStyles: [
      { type: 'fade-out', duration: 5, elements: ['message', 'credits'], animation: { messageDelay: 0, photosDelay: 2, easing: 'easeInOut' } },
      { type: 'scroll-credits', duration: 6, elements: ['message', 'credits', 'photos'], animation: { messageDelay: 0, photosDelay: 2, easing: 'linear' } },
    ],
    introPrompts: [
      '선율이 시작되는 순간',
      '음악으로 전하는 마음',
      '무대 위의 아름다운 하모니',
    ],
    outroPrompts: [
      '여운이 남는 감동의 연주',
      '음악으로 하나가 된 우리',
      '다음 무대를 기대하며',
    ],
  },
];
