import { Theme } from '@/types/theme';

export const EVENT_THEMES: Theme[] = [
  {
    id: 'NEW_YEAR',
    name: '새해/신년',
    nameEn: 'New Year',
    icon: '🎆',
    emoji: '🎊',
    description: '새해의 시작을 축하해요',
    category: 'event',
    subCategory: 'holiday',
    colors: {
      primary: '#DC2626',
      secondary: '#EF4444',
      accent: '#FCA5A5',
      background: '#FEF2F2',
      text: '#7F1D1D',
      gradient: 'linear-gradient(135deg, #DC2626 0%, #FBBF24 100%)',
    },
    fonts: {
      title: 'GmarketSans',
      body: 'Pretendard',
      accent: 'GmarketSans',
    },
    defaultMusic: 'newyear-festive',
    defaultTransition: 'crossDissolve',
    defaultEffect: 'kenburns-zoom-in',
    titleTemplate: '{year} 새해 복 많이 받으세요!',
    defaultEnding: '새해 복 많이 받으세요! 🎆\n행복한 한 해 되세요! 🎊',
    narrationPrompt: `당신은 새해/신년 영상의 축하하는 나레이터입니다.
새해의 희망과 기쁨을 밝게 전달하세요.
축제 분위기와 희망찬 톤으로 진행하세요.`,
    narrationStyle: 'festive, hopeful, celebratory',
    suggestedDuration: 60,
    suggestedPhotoCount: { min: 15, max: 40 },
    tags: ['새해', '신년', '축하', '희망', '복'],
    premium: false,
    introStyles: [
      { type: 'explosion', duration: 4, elements: ['title', 'particles', 'gradient-bg'], animation: { titleDelay: 0.3, subtitleDelay: 1.5, easing: 'easeOutBack' } },
      { type: 'neon-glow', duration: 5, elements: ['title', 'subtitle'], animation: { titleDelay: 0.5, subtitleDelay: 2, easing: 'easeOut' } },
    ],
    outroStyles: [
      { type: 'fireworks', duration: 5, elements: ['message', 'photos'], animation: { messageDelay: 0.5, photosDelay: 2, easing: 'easeOut' } },
      { type: 'confetti', duration: 4, elements: ['message'], animation: { messageDelay: 0.5, photosDelay: 1.5, easing: 'easeOut' } },
    ],
    introPrompts: [
      '새로운 시작의 첫 날',
      '희망찬 새해가 밝았습니다',
      '행복한 한 해의 시작',
    ],
    outroPrompts: [
      '새해 복 많이 받으세요',
      '행복한 한 해 되시길',
      '꿈이 이루어지는 한 해',
    ],
  },
  {
    id: 'CHRISTMAS',
    name: '크리스마스',
    nameEn: 'Christmas',
    icon: '🎄',
    emoji: '🎅',
    description: '따뜻한 크리스마스',
    category: 'event',
    subCategory: 'holiday',
    colors: {
      primary: '#16A34A',
      secondary: '#22C55E',
      accent: '#DC2626',
      background: '#F0FDF4',
      text: '#14532D',
      gradient: 'linear-gradient(135deg, #16A34A 0%, #DC2626 100%)',
    },
    fonts: {
      title: 'GmarketSans',
      body: 'Pretendard',
      accent: 'GmarketSans',
    },
    defaultMusic: 'christmas-joyful',
    defaultTransition: 'crossDissolve',
    defaultEffect: 'kenburns-zoom-in',
    titleTemplate: 'Merry Christmas! 🎄',
    defaultEnding: '메리 크리스마스! 🎄\n사랑하는 사람들과 함께 🎅',
    narrationPrompt: `당신은 크리스마스 영상의 따뜻한 나레이터입니다.
크리스마스의 따뜻함과 기쁨을 전달하세요.
따뜻하고 축제 분위기의 톤으로 진행하세요.`,
    narrationStyle: 'warm, festive, joyful',
    suggestedDuration: 60,
    suggestedPhotoCount: { min: 15, max: 40 },
    tags: ['크리스마스', '성탄절', '겨울', '가족', '선물'],
    premium: false,
    introStyles: [
      { type: 'particles', duration: 5, elements: ['title', 'subtitle', 'particles'], animation: { titleDelay: 1, subtitleDelay: 2.5, easing: 'easeOut' } },
      { type: 'floating', duration: 5, elements: ['title', 'gradient-bg'], animation: { titleDelay: 1, subtitleDelay: 2.5, easing: 'easeOutSine' } },
    ],
    outroStyles: [
      { type: 'confetti', duration: 4, elements: ['message', 'photos'], animation: { messageDelay: 0.5, photosDelay: 1.5, easing: 'easeOut' } },
      { type: 'heart-gather', duration: 5, elements: ['message', 'photos'], animation: { messageDelay: 0.5, photosDelay: 1.5, easing: 'easeOut' } },
    ],
    introPrompts: [
      '따뜻한 크리스마스의 순간',
      '사랑이 가득한 계절',
      '함께하는 크리스마스',
    ],
    outroPrompts: [
      '메리 크리스마스',
      '사랑하는 사람들과 함께',
      '행복한 연말 보내세요',
    ],
  },
  {
    id: 'VALENTINES',
    name: '발렌타인/화이트데이',
    nameEn: 'Valentine\'s Day',
    icon: '💝',
    emoji: '💕',
    description: '사랑을 전하는 날',
    category: 'event',
    subCategory: 'love',
    colors: {
      primary: '#EC4899',
      secondary: '#F472B6',
      accent: '#FECDD3',
      background: '#FDF2F8',
      text: '#9D174D',
      gradient: 'linear-gradient(135deg, #EC4899 0%, #FECDD3 100%)',
    },
    fonts: {
      title: 'GmarketSans',
      body: 'Pretendard',
      accent: 'GmarketSans',
    },
    defaultMusic: 'valentine-romantic',
    defaultTransition: 'crossDissolve',
    defaultEffect: 'kenburns-zoom-in',
    titleTemplate: 'Happy Valentine\'s Day! 💝',
    defaultEnding: '사랑해요 💕\n언제나 당신 곁에 있을게요 💝',
    narrationPrompt: `당신은 발렌타인/화이트데이 영상의 로맨틱한 나레이터입니다.
사랑의 감정을 달콤하고 진심 어리게 전달하세요.
로맨틱하고 달콤한 톤으로 진행하세요.`,
    narrationStyle: 'romantic, sweet, loving',
    suggestedDuration: 60,
    suggestedPhotoCount: { min: 15, max: 35 },
    tags: ['발렌타인', '화이트데이', '사랑', '연인', '로맨틱'],
    premium: false,
    introStyles: [
      { type: 'floating', duration: 5, elements: ['title', 'particles', 'gradient-bg'], animation: { titleDelay: 1, subtitleDelay: 2.5, easing: 'easeOutSine' } },
      { type: 'elegant-fade', duration: 5, elements: ['title', 'subtitle'], animation: { titleDelay: 1, subtitleDelay: 2.5, easing: 'easeInOut' } },
    ],
    outroStyles: [
      { type: 'heart-gather', duration: 5, elements: ['message', 'photos'], animation: { messageDelay: 0.5, photosDelay: 1.5, easing: 'easeOut' } },
      { type: 'flower-bloom', duration: 5, elements: ['message', 'photos'], animation: { messageDelay: 0.5, photosDelay: 2, easing: 'easeOut' } },
    ],
    introPrompts: [
      '사랑을 전하는 특별한 날',
      '당신을 위한 마음',
      '사랑이 가득한 순간',
    ],
    outroPrompts: [
      '사랑해요',
      '언제나 당신 곁에',
      '영원히 함께',
    ],
  },
  {
    id: 'HALLOWEEN',
    name: '할로윈',
    nameEn: 'Halloween',
    icon: '🎃',
    emoji: '👻',
    description: '으스스한 할로윈 파티',
    category: 'event',
    subCategory: 'holiday',
    colors: {
      primary: '#EA580C',
      secondary: '#F97316',
      accent: '#6B21A8',
      background: '#1C1917',
      text: '#FBBF24',
      gradient: 'linear-gradient(135deg, #EA580C 0%, #6B21A8 100%)',
    },
    fonts: {
      title: 'GmarketSans',
      body: 'Pretendard',
      accent: 'GmarketSans',
    },
    defaultMusic: 'halloween-spooky',
    defaultTransition: 'glitch',
    defaultEffect: 'kenburns-zoom-in',
    titleTemplate: 'Happy Halloween! 🎃',
    defaultEnding: 'Happy Halloween! 🎃\nTrick or Treat! 👻',
    narrationPrompt: `당신은 할로윈 영상의 으스스한 나레이터입니다.
할로윈의 재미있고 스릴 있는 분위기를 전달하세요.
장난스럽고 으스스한 톤으로 진행하세요.`,
    narrationStyle: 'spooky, playful, fun',
    suggestedDuration: 60,
    suggestedPhotoCount: { min: 15, max: 40 },
    tags: ['할로윈', '코스튬', '파티', '호박', '귀신'],
    premium: false,
    introStyles: [
      { type: 'glitch', duration: 4, elements: ['title', 'particles'], animation: { titleDelay: 0.3, subtitleDelay: 1.5, easing: 'easeOutExpo' } },
      { type: 'explosion', duration: 4, elements: ['title', 'gradient-bg'], animation: { titleDelay: 0.5, subtitleDelay: 1.5, easing: 'easeOutBack' } },
    ],
    outroStyles: [
      { type: 'confetti', duration: 4, elements: ['message', 'photos'], animation: { messageDelay: 0.5, photosDelay: 1.5, easing: 'easeOut' } },
      { type: 'photo-collage', duration: 5, elements: ['message', 'photos'], animation: { messageDelay: 0.5, photosDelay: 0, easing: 'easeOut' } },
    ],
    introPrompts: [
      '으스스한 밤이 시작됩니다',
      '할로윈 파티에 오신 것을 환영합니다',
      '공포와 즐거움이 가득한 밤',
    ],
    outroPrompts: [
      'Happy Halloween!',
      'Trick or Treat!',
      '내년 할로윈에 또 만나요',
    ],
  },
  {
    id: 'CONCERT',
    name: '콘서트/공연',
    nameEn: 'Concert',
    icon: '🎤',
    emoji: '🎸',
    description: '열정의 무대',
    category: 'event',
    subCategory: 'entertainment',
    colors: {
      primary: '#7C3AED',
      secondary: '#8B5CF6',
      accent: '#A78BFA',
      background: '#0F0F0F',
      text: '#FFFFFF',
      gradient: 'linear-gradient(135deg, #7C3AED 0%, #EC4899 100%)',
    },
    fonts: {
      title: 'GmarketSans',
      body: 'Pretendard',
      accent: 'GmarketSans',
    },
    defaultMusic: 'concert-dynamic',
    defaultTransition: 'zoomIn',
    defaultEffect: 'kenburns-zoom-in',
    titleTemplate: '{artist} 콘서트',
    defaultEnding: '최고의 공연이었습니다! 🎤\n다음 공연에서 또 만나요! 🎸',
    narrationPrompt: `당신은 콘서트/공연 영상의 역동적인 나레이터입니다.
공연의 열기와 감동을 생동감 있게 전달하세요.
역동적이고 흥분되는 톤으로 진행하세요.`,
    narrationStyle: 'dynamic, exciting, passionate',
    suggestedDuration: 120,
    suggestedPhotoCount: { min: 25, max: 60 },
    tags: ['콘서트', '공연', '라이브', '음악', '아티스트'],
    premium: true,
    introStyles: [
      { type: 'explosion', duration: 4, elements: ['title', 'particles', 'gradient-bg'], animation: { titleDelay: 0.3, subtitleDelay: 1.5, easing: 'easeOutBack' } },
      { type: 'glitch', duration: 4, elements: ['title', 'subtitle'], animation: { titleDelay: 0.3, subtitleDelay: 1.5, easing: 'easeOutExpo' } },
      { type: 'neon-glow', duration: 5, elements: ['title', 'logo'], animation: { titleDelay: 0.5, subtitleDelay: 2, easing: 'easeOut' } },
    ],
    outroStyles: [
      { type: 'fireworks', duration: 5, elements: ['message', 'photos'], animation: { messageDelay: 0.5, photosDelay: 2, easing: 'easeOut' } },
      { type: 'photo-collage', duration: 5, elements: ['message', 'photos'], animation: { messageDelay: 0.5, photosDelay: 0, easing: 'easeOut' } },
    ],
    introPrompts: [
      '열정의 무대가 시작됩니다',
      '잊지 못할 공연의 순간',
      '음악으로 하나되는 밤',
    ],
    outroPrompts: [
      '최고의 공연이었습니다',
      '다음 공연에서 또 만나요',
      '함께해서 행복했습니다',
    ],
  },
  {
    id: 'SPORTS_EVENT',
    name: '스포츠 이벤트',
    nameEn: 'Sports Event',
    icon: '⚽',
    emoji: '🏆',
    description: '열정의 경기장',
    category: 'event',
    subCategory: 'sports',
    colors: {
      primary: '#059669',
      secondary: '#10B981',
      accent: '#34D399',
      background: '#ECFDF5',
      text: '#064E3B',
      gradient: 'linear-gradient(135deg, #059669 0%, #34D399 100%)',
    },
    fonts: {
      title: 'GmarketSans',
      body: 'Pretendard',
      accent: 'GmarketSans',
    },
    defaultMusic: 'sports-energetic',
    defaultTransition: 'slideLeft',
    defaultEffect: 'kenburns-pan-left',
    titleTemplate: '{event} {year}',
    defaultEnding: '열정적인 경기였습니다! ⚽\n다음 경기도 기대해주세요! 🏆',
    narrationPrompt: `당신은 스포츠 이벤트 영상의 열정적인 나레이터입니다.
경기의 긴장감과 흥분을 생동감 있게 전달하세요.
역동적이고 열정적인 톤으로 진행하세요.`,
    narrationStyle: 'dynamic, exciting, passionate',
    suggestedDuration: 90,
    suggestedPhotoCount: { min: 20, max: 50 },
    tags: ['스포츠', '경기', '응원', '열정', '팀'],
    premium: false,
    introStyles: [
      { type: 'dynamic-zoom', duration: 4, elements: ['title', 'subtitle', 'gradient-bg'], animation: { titleDelay: 0.3, subtitleDelay: 1.2, easing: 'easeOutExpo' } },
      { type: 'split', duration: 4, elements: ['title', 'logo'], animation: { titleDelay: 0.5, subtitleDelay: 1.5, easing: 'easeOut' } },
    ],
    outroStyles: [
      { type: 'fireworks', duration: 5, elements: ['message', 'photos'], animation: { messageDelay: 0.5, photosDelay: 2, easing: 'easeOut' } },
      { type: 'photo-collage', duration: 5, elements: ['message', 'photos'], animation: { messageDelay: 0.5, photosDelay: 0, easing: 'easeOut' } },
    ],
    introPrompts: [
      '열정의 무대가 펼쳐집니다',
      '최고의 순간을 함께',
      '승리를 향한 도전',
    ],
    outroPrompts: [
      '열정적인 경기였습니다',
      '모든 선수들에게 박수를',
      '다음 경기도 기대해주세요',
    ],
  },
  {
    id: 'ANNIVERSARY',
    name: '기념일',
    nameEn: 'Anniversary',
    icon: '📅',
    emoji: '💕',
    description: '특별한 날을 기념해요',
    category: 'event',
    subCategory: 'celebration',
    colors: {
      primary: '#F472B6',
      secondary: '#FB7185',
      accent: '#FECDD3',
      background: '#FFF1F2',
      text: '#9D174D',
      gradient: 'linear-gradient(135deg, #F472B6 0%, #FECDD3 100%)',
    },
    fonts: {
      title: 'GmarketSans',
      body: 'Pretendard',
      accent: 'GmarketSans',
    },
    defaultMusic: 'anniversary-romantic',
    defaultTransition: 'crossDissolve',
    defaultEffect: 'kenburns-zoom-in',
    titleTemplate: '{years}주년 기념일',
    defaultEnding: '특별한 기념일을 축하합니다! 📅\n앞으로도 함께 💕',
    narrationPrompt: `당신은 기념일 영상의 진심 어린 나레이터입니다.
특별한 날의 의미와 함께한 시간의 소중함을 전달하세요.
따뜻하고 감사하는 톤으로 진행하세요.`,
    narrationStyle: 'warm, grateful, loving',
    suggestedDuration: 60,
    suggestedPhotoCount: { min: 15, max: 40 },
    tags: ['기념일', '축하', '사랑', '특별', '함께'],
    premium: false,
    introStyles: [
      { type: 'elegant-fade', duration: 5, elements: ['title', 'subtitle', 'gradient-bg'], animation: { titleDelay: 1, subtitleDelay: 2.5, easing: 'easeInOut' } },
      { type: 'floating', duration: 5, elements: ['title', 'particles'], animation: { titleDelay: 1, subtitleDelay: 2.5, easing: 'easeOutSine' } },
    ],
    outroStyles: [
      { type: 'heart-gather', duration: 5, elements: ['message', 'photos'], animation: { messageDelay: 0.5, photosDelay: 1.5, easing: 'easeOut' } },
      { type: 'polaroid-stack', duration: 5, elements: ['message', 'photos'], animation: { messageDelay: 0, photosDelay: 1.5, easing: 'easeOutBack' } },
    ],
    introPrompts: [
      '특별한 날을 기념하며',
      '함께한 소중한 시간',
      '사랑으로 채워진 날들',
    ],
    outroPrompts: [
      '앞으로도 함께',
      '영원히 기억될 순간',
      '사랑합니다',
    ],
  },
  {
    id: 'CHARITY_EVENT',
    name: '자선/봉사활동',
    nameEn: 'Charity Event',
    icon: '🤲',
    emoji: '💝',
    description: '따뜻한 마음을 나눠요',
    category: 'event',
    subCategory: 'charity',
    colors: {
      primary: '#0891B2',
      secondary: '#06B6D4',
      accent: '#22D3EE',
      background: '#ECFEFF',
      text: '#155E75',
      gradient: 'linear-gradient(135deg, #0891B2 0%, #22D3EE 100%)',
    },
    fonts: {
      title: 'GmarketSans',
      body: 'Pretendard',
      accent: 'GmarketSans',
    },
    defaultMusic: 'charity-hopeful',
    defaultTransition: 'crossDissolve',
    defaultEffect: 'kenburns-zoom-in',
    titleTemplate: '{event} 봉사활동',
    defaultEnding: '함께해주셔서 감사합니다! 🤲\n작은 나눔이 큰 변화를 만듭니다 💝',
    narrationPrompt: `당신은 자선/봉사활동 영상의 감사하는 나레이터입니다.
나눔의 가치와 봉사의 보람을 진심으로 전달하세요.
따뜻하고 감사하는 톤으로 진행하세요.`,
    narrationStyle: 'grateful, warm, inspiring',
    suggestedDuration: 90,
    suggestedPhotoCount: { min: 20, max: 50 },
    tags: ['봉사', '자선', '나눔', '기부', '따뜻함'],
    premium: false,
    introStyles: [
      { type: 'floating', duration: 5, elements: ['title', 'subtitle', 'gradient-bg'], animation: { titleDelay: 1, subtitleDelay: 2.5, easing: 'easeOutSine' } },
      { type: 'fade-zoom', duration: 4, elements: ['title', 'date'], animation: { titleDelay: 0.5, subtitleDelay: 1.5, easing: 'easeOut' } },
    ],
    outroStyles: [
      { type: 'thank-you', duration: 5, elements: ['message', 'credits'], animation: { messageDelay: 0, photosDelay: 2, easing: 'easeInOut' } },
      { type: 'heart-gather', duration: 5, elements: ['message', 'photos'], animation: { messageDelay: 0.5, photosDelay: 1.5, easing: 'easeOut' } },
    ],
    introPrompts: [
      '따뜻한 마음이 모이는 곳',
      '나눔으로 행복을 전합니다',
      '함께하는 봉사의 보람',
    ],
    outroPrompts: [
      '함께해주셔서 감사합니다',
      '작은 나눔이 큰 변화를',
      '더 많은 나눔을 기대하며',
    ],
  },
  {
    id: 'FRIENDSHIP',
    name: '우정/친구',
    nameEn: 'Friendship',
    icon: '👯',
    emoji: '💜',
    description: '소중한 친구와의 추억',
    category: 'event',
    subCategory: 'friendship',
    colors: {
      primary: '#8B5CF6',
      secondary: '#A78BFA',
      accent: '#C4B5FD',
      background: '#F5F3FF',
      text: '#5B21B6',
      gradient: 'linear-gradient(135deg, #8B5CF6 0%, #C4B5FD 100%)',
    },
    fonts: {
      title: 'GmarketSans',
      body: 'Pretendard',
      accent: 'GmarketSans',
    },
    defaultMusic: 'friendship-cheerful',
    defaultTransition: 'slideRight',
    defaultEffect: 'kenburns-pan-right',
    titleTemplate: '우리의 우정 이야기',
    defaultEnding: '영원한 우리의 우정! 👯\n언제나 함께야! 💜',
    narrationPrompt: `당신은 우정 영상의 밝은 나레이터입니다.
친구와의 소중한 추억과 유대감을 담아주세요.
밝고 정감 있는 톤으로 진행하세요.`,
    narrationStyle: 'friendly, cheerful, nostalgic',
    suggestedDuration: 90,
    suggestedPhotoCount: { min: 20, max: 50 },
    tags: ['우정', '친구', '추억', '함께', '영원'],
    premium: false,
    introStyles: [
      { type: 'bounce', duration: 4, elements: ['title', 'subtitle', 'particles'], animation: { titleDelay: 0.3, subtitleDelay: 1.5, easing: 'easeOutBounce' } },
      { type: 'floating', duration: 4, elements: ['title', 'gradient-bg'], animation: { titleDelay: 0.5, subtitleDelay: 1.5, easing: 'easeOutSine' } },
    ],
    outroStyles: [
      { type: 'photo-collage', duration: 5, elements: ['message', 'photos'], animation: { messageDelay: 0.5, photosDelay: 0, easing: 'easeOut' } },
      { type: 'heart-gather', duration: 5, elements: ['message', 'photos'], animation: { messageDelay: 0.5, photosDelay: 1.5, easing: 'easeOut' } },
    ],
    introPrompts: [
      '소중한 친구들과 함께',
      '우리의 특별한 이야기',
      '영원히 기억될 우정',
    ],
    outroPrompts: [
      '언제나 함께야',
      '영원한 우리의 우정',
      '다음에 또 만나',
    ],
  },
  {
    id: 'TRAVEL_VLOG',
    name: '여행 브이로그',
    nameEn: 'Travel Vlog',
    icon: '🗺️',
    emoji: '✈️',
    description: '세계를 누비는 여행기',
    category: 'event',
    subCategory: 'travel',
    colors: {
      primary: '#0EA5E9',
      secondary: '#38BDF8',
      accent: '#7DD3FC',
      background: '#F0F9FF',
      text: '#0C4A6E',
      gradient: 'linear-gradient(135deg, #0EA5E9 0%, #7DD3FC 100%)',
    },
    fonts: {
      title: 'GmarketSans',
      body: 'Pretendard',
      accent: 'GmarketSans',
    },
    defaultMusic: 'travel-adventure',
    defaultTransition: 'slideUp',
    defaultEffect: 'kenburns-pan-right',
    titleTemplate: '{destination} 여행기',
    defaultEnding: '잊지 못할 여행이었습니다! 🗺️\n다음 여행도 기대해주세요! ✈️',
    narrationPrompt: `당신은 여행 브이로그의 활기찬 나레이터입니다.
여행지의 매력과 새로운 발견의 즐거움을 전달하세요.
모험적이고 밝은 톤으로 진행하세요.`,
    narrationStyle: 'adventurous, lively, enthusiastic',
    suggestedDuration: 120,
    suggestedPhotoCount: { min: 30, max: 80 },
    tags: ['여행', '브이로그', '모험', '세계', '탐험'],
    premium: false,
    introStyles: [
      { type: 'dynamic-zoom', duration: 4, elements: ['title', 'subtitle', 'gradient-bg'], animation: { titleDelay: 0.3, subtitleDelay: 1.2, easing: 'easeOut' } },
      { type: 'slide-up', duration: 4, elements: ['title', 'date'], animation: { titleDelay: 0.5, subtitleDelay: 1.5, easing: 'easeOut' } },
      { type: 'photo-stack', duration: 5, elements: ['title', 'particles'], animation: { titleDelay: 1, subtitleDelay: 2.5, easing: 'easeOutBack' } },
    ],
    outroStyles: [
      { type: 'flying-photos', duration: 5, elements: ['message', 'photos'], animation: { messageDelay: 0.5, photosDelay: 0, easing: 'easeInOut' } },
      { type: 'mosaic', duration: 5, elements: ['message', 'photos'], animation: { messageDelay: 0.5, photosDelay: 0, easing: 'easeOut' } },
      { type: 'photo-collage', duration: 5, elements: ['message', 'photos'], animation: { messageDelay: 0.5, photosDelay: 0, easing: 'easeOut' } },
    ],
    introPrompts: [
      '새로운 모험이 시작됩니다',
      '세계를 누비는 여행',
      '잊지 못할 순간들',
    ],
    outroPrompts: [
      '잊지 못할 여행이었습니다',
      '다음 여행도 기대해주세요',
      '함께해서 더 빛났던 여행',
    ],
  },
];
