import { Theme } from '@/types/theme';

export const FAMILY_THEMES: Theme[] = [
  {
    id: 'WEDDING',
    name: '결혼식',
    nameEn: 'Wedding',
    icon: '💒',
    emoji: '💍',
    description: '영원한 사랑의 약속',
    category: 'family',
    subCategory: 'wedding',
    colors: {
      primary: '#F472B6',
      secondary: '#FB7185',
      accent: '#FECDD3',
      background: '#FFF1F2',
      text: '#881337',
      gradient: 'linear-gradient(135deg, #F472B6 0%, #FECDD3 100%)',
    },
    fonts: {
      title: 'GmarketSans',
      body: 'Pretendard',
      accent: 'GmarketSans',
    },
    defaultMusic: 'wedding-romantic',
    defaultTransition: 'crossDissolve',
    defaultEffect: 'kenburns-zoom-in',
    titleTemplate: '{groom} ♥ {bride}의 결혼식',
    defaultEnding: '영원한 사랑을 약속합니다.\n두 사람의 행복을 축복합니다 💒💕',
    narrationPrompt: `당신은 결혼식 영상의 로맨틱한 나레이터입니다.
두 사람의 사랑 이야기, 결혼식의 감동, 축복의 메시지를 담아주세요.
로맨틱하고 감동적인 톤으로 진행하세요.`,
    narrationStyle: 'romantic, elegant, heartfelt',
    suggestedDuration: 180,
    suggestedPhotoCount: { min: 40, max: 100 },
    tags: ['결혼식', '웨딩', '사랑', '축복', '영원'],
    premium: true,
    introStyles: [
      { type: 'elegant-fade', duration: 6, elements: ['title', 'subtitle', 'particles', 'gradient-bg'], animation: { titleDelay: 1.5, subtitleDelay: 3, easing: 'easeInOut' } },
      { type: 'floating', duration: 5, elements: ['title', 'date', 'particles'], animation: { titleDelay: 1, subtitleDelay: 2.5, easing: 'easeOutSine' } },
      { type: 'curtain', duration: 6, elements: ['title', 'subtitle'], animation: { titleDelay: 2, subtitleDelay: 4, easing: 'easeInOutQuart' } },
    ],
    outroStyles: [
      { type: 'heart-gather', duration: 6, elements: ['message', 'photos'], animation: { messageDelay: 0.5, photosDelay: 1.5, easing: 'easeOut' } },
      { type: 'flower-bloom', duration: 5, elements: ['message', 'photos'], animation: { messageDelay: 0.5, photosDelay: 2, easing: 'easeOut' } },
      { type: 'polaroid-stack', duration: 6, elements: ['message', 'photos', 'credits'], animation: { messageDelay: 0, photosDelay: 1.5, easing: 'easeOutBack' } },
    ],
    introPrompts: [
      '사랑으로 시작되는 영원한 여정',
      '두 사람의 아름다운 이야기',
      '축복 속에 피어나는 사랑',
    ],
    outroPrompts: [
      '영원히 함께할 두 사람을 축복하며',
      '사랑이 영원하길 바랍니다',
      '행복한 시작을 축하합니다',
    ],
  },
  {
    id: 'BIRTHDAY_CHILD',
    name: '어린이 생일',
    nameEn: 'Child Birthday',
    icon: '🎂',
    emoji: '🎈',
    description: '소중한 아이의 생일 파티',
    category: 'family',
    subCategory: 'birthday',
    colors: {
      primary: '#F59E0B',
      secondary: '#FBBF24',
      accent: '#FDE68A',
      background: '#FFFBEB',
      text: '#78350F',
      gradient: 'linear-gradient(135deg, #F59E0B 0%, #FDE68A 100%)',
    },
    fonts: {
      title: 'GmarketSans',
      body: 'Pretendard',
      accent: 'GmarketSans',
    },
    defaultMusic: 'birthday-cheerful',
    defaultTransition: 'slideRight',
    defaultEffect: 'kenburns-zoom-in',
    titleTemplate: '{name}의 {age}번째 생일',
    defaultEnding: '생일 축하해! 🎂\n사랑하는 {name}, 건강하게 자라줘! 💕',
    narrationPrompt: `당신은 어린이 생일 파티 영상의 밝은 나레이터입니다.
아이의 성장과 생일의 기쁨을 담아주세요.
밝고 즐거운 톤으로 진행하세요.`,
    narrationStyle: 'cheerful, playful, celebratory',
    suggestedDuration: 60,
    suggestedPhotoCount: { min: 15, max: 40 },
    tags: ['생일', '어린이', '파티', '축하', '성장'],
    premium: false,
    introStyles: [
      { type: 'bounce', duration: 4, elements: ['title', 'subtitle', 'particles'], animation: { titleDelay: 0.3, subtitleDelay: 1.5, easing: 'easeOutBounce' } },
      { type: 'explosion', duration: 4, elements: ['title', 'particles', 'gradient-bg'], animation: { titleDelay: 0.5, subtitleDelay: 1.5, easing: 'easeOutBack' } },
    ],
    outroStyles: [
      { type: 'balloon', duration: 4, elements: ['message', 'photos'], animation: { messageDelay: 0.5, photosDelay: 1.5, easing: 'easeOutBack' } },
      { type: 'confetti', duration: 4, elements: ['message', 'photos'], animation: { messageDelay: 0.5, photosDelay: 1.5, easing: 'easeOut' } },
    ],
    introPrompts: [
      '특별한 날의 특별한 주인공',
      '신나는 생일 파티가 시작됩니다',
      '사랑받는 우리 아이의 생일',
    ],
    outroPrompts: [
      '매년 더 빛나는 아이로 자라길',
      '사랑으로 가득한 한 해가 되길',
      '생일 축하해, 사랑해!',
    ],
  },
  {
    id: 'BIRTHDAY_ADULT',
    name: '성인 생일',
    nameEn: 'Adult Birthday',
    icon: '🎁',
    emoji: '🥳',
    description: '소중한 사람의 생일',
    category: 'family',
    subCategory: 'birthday',
    colors: {
      primary: '#8B5CF6',
      secondary: '#A78BFA',
      accent: '#C4B5FD',
      background: '#F5F3FF',
      text: '#5B21B6',
      gradient: 'linear-gradient(135deg, #8B5CF6 0%, #C4B5FD 100%)',
    },
    fonts: {
      title: 'GmarketSans',
      body: 'Pretendard',
      accent: 'GmarketSans',
    },
    defaultMusic: 'birthday-elegant',
    defaultTransition: 'crossDissolve',
    defaultEffect: 'kenburns-pan-right',
    titleTemplate: '{name}의 생일을 축하합니다',
    defaultEnding: '생일 축하합니다! 🎂\n행복한 한 해가 되시길 바랍니다 🎁',
    narrationPrompt: `당신은 성인 생일 영상의 나레이터입니다.
감사와 축하의 마음을 진심 어리게 전달하세요.
따뜻하고 진심 어린 톤으로 진행하세요.`,
    narrationStyle: 'warm, sincere, celebratory',
    suggestedDuration: 90,
    suggestedPhotoCount: { min: 20, max: 50 },
    tags: ['생일', '축하', '감사', '행복', '기념일'],
    premium: false,
    introStyles: [
      { type: 'elegant-fade', duration: 5, elements: ['title', 'subtitle', 'gradient-bg'], animation: { titleDelay: 1, subtitleDelay: 2.5, easing: 'easeInOut' } },
      { type: 'floating', duration: 4, elements: ['title', 'particles'], animation: { titleDelay: 0.5, subtitleDelay: 1.5, easing: 'easeOut' } },
    ],
    outroStyles: [
      { type: 'confetti', duration: 4, elements: ['message', 'photos'], animation: { messageDelay: 0.5, photosDelay: 1.5, easing: 'easeOut' } },
      { type: 'photo-collage', duration: 5, elements: ['message', 'photos'], animation: { messageDelay: 0.5, photosDelay: 0, easing: 'easeOut' } },
    ],
    introPrompts: [
      '특별한 하루를 시작하며',
      '감사와 축하의 마음을 담아',
      '행복한 생일을 축하합니다',
    ],
    outroPrompts: [
      '늘 행복하시길 바랍니다',
      '사랑하는 마음을 담아',
      '멋진 한 해가 되시길',
    ],
  },
  {
    id: 'BABY_100DAYS',
    name: '백일잔치',
    nameEn: '100 Days Celebration',
    icon: '👶',
    emoji: '🎀',
    description: '사랑스러운 아기의 백일',
    category: 'family',
    subCategory: 'baby',
    colors: {
      primary: '#F9A8D4',
      secondary: '#FBCFE8',
      accent: '#FCE7F3',
      background: '#FDF2F8',
      text: '#9D174D',
      gradient: 'linear-gradient(135deg, #F9A8D4 0%, #FCE7F3 100%)',
    },
    fonts: {
      title: 'GmarketSans',
      body: 'Pretendard',
      accent: 'GmarketSans',
    },
    defaultMusic: 'baby-gentle',
    defaultTransition: 'fade',
    defaultEffect: 'kenburns-zoom-in',
    titleTemplate: '{name}의 백일을 축하해요',
    defaultEnding: '백일 축하해, {name}! 👶\n건강하게 자라렴 💕',
    narrationPrompt: `당신은 백일잔치 영상의 다정한 나레이터입니다.
아기의 탄생부터 백일까지의 성장을 사랑스럽게 담아주세요.
다정하고 축복 어린 톤으로 진행하세요.`,
    narrationStyle: 'gentle, loving, blessed',
    suggestedDuration: 60,
    suggestedPhotoCount: { min: 15, max: 35 },
    tags: ['백일', '아기', '축하', '성장', '사랑'],
    premium: false,
    introStyles: [
      { type: 'floating', duration: 5, elements: ['title', 'subtitle', 'particles'], animation: { titleDelay: 1, subtitleDelay: 2.5, easing: 'easeOutSine' } },
      { type: 'fade-zoom', duration: 4, elements: ['title', 'date'], animation: { titleDelay: 0.5, subtitleDelay: 1.5, easing: 'easeOut' } },
    ],
    outroStyles: [
      { type: 'heart-gather', duration: 5, elements: ['message', 'photos'], animation: { messageDelay: 0.5, photosDelay: 1.5, easing: 'easeOut' } },
      { type: 'polaroid-stack', duration: 5, elements: ['message', 'photos'], animation: { messageDelay: 0, photosDelay: 1.5, easing: 'easeOutBack' } },
    ],
    introPrompts: [
      '세상에 온 지 100일',
      '사랑 가득한 백일의 순간',
      '우리 아기의 첫 번째 기념일',
    ],
    outroPrompts: [
      '건강하게 무럭무럭 자라렴',
      '사랑으로 가득한 미래가 되길',
      '세상에서 가장 사랑받는 아기',
    ],
  },
  {
    id: 'BABY_FIRST_BIRTHDAY',
    name: '돌잔치',
    nameEn: 'First Birthday',
    icon: '🎀',
    emoji: '🎂',
    description: '첫 번째 생일의 기적',
    category: 'family',
    subCategory: 'baby',
    colors: {
      primary: '#EC4899',
      secondary: '#F472B6',
      accent: '#F9A8D4',
      background: '#FDF2F8',
      text: '#831843',
      gradient: 'linear-gradient(135deg, #EC4899 0%, #F9A8D4 100%)',
    },
    fonts: {
      title: 'GmarketSans',
      body: 'Pretendard',
      accent: 'GmarketSans',
    },
    defaultMusic: 'baby-celebration',
    defaultTransition: 'crossDissolve',
    defaultEffect: 'kenburns-zoom-in',
    titleTemplate: '{name}의 첫 번째 생일',
    defaultEnding: '첫 돌을 축하해, {name}! 🎂\n앞으로도 건강하고 행복하게! 💕',
    narrationPrompt: `당신은 돌잔치 영상의 다정한 나레이터입니다.
아기의 첫 1년 성장 과정과 돌잔치의 기쁨을 담아주세요.
사랑스럽고 축복 어린 톤으로 진행하세요.`,
    narrationStyle: 'loving, celebratory, blessed',
    suggestedDuration: 90,
    suggestedPhotoCount: { min: 25, max: 60 },
    tags: ['돌잔치', '첫생일', '아기', '성장', '축하'],
    premium: false,
    introStyles: [
      { type: 'bounce', duration: 5, elements: ['title', 'subtitle', 'particles'], animation: { titleDelay: 0.5, subtitleDelay: 2, easing: 'easeOutBounce' } },
      { type: 'floating', duration: 5, elements: ['title', 'date', 'gradient-bg'], animation: { titleDelay: 1, subtitleDelay: 2.5, easing: 'easeOutSine' } },
    ],
    outroStyles: [
      { type: 'heart-gather', duration: 5, elements: ['message', 'photos'], animation: { messageDelay: 0.5, photosDelay: 1.5, easing: 'easeOut' } },
      { type: 'balloon', duration: 5, elements: ['message', 'photos'], animation: { messageDelay: 0.5, photosDelay: 1.5, easing: 'easeOutBack' } },
    ],
    introPrompts: [
      '세상에서 가장 소중한 첫 돌',
      '365일간의 사랑스러운 성장',
      '축복 속에 맞이하는 첫 생일',
    ],
    outroPrompts: [
      '앞으로도 건강하게 자라렴',
      '사랑으로 가득한 인생이 되길',
      '우리 가족의 보물, 사랑해',
    ],
  },
  {
    id: 'BABY_GROWTH',
    name: '아기 성장 앨범',
    nameEn: 'Baby Growth Album',
    icon: '📒',
    emoji: '👶',
    description: '아기의 성장 과정을 담아요',
    category: 'family',
    subCategory: 'baby',
    colors: {
      primary: '#60A5FA',
      secondary: '#93C5FD',
      accent: '#BFDBFE',
      background: '#EFF6FF',
      text: '#1E40AF',
      gradient: 'linear-gradient(135deg, #60A5FA 0%, #BFDBFE 100%)',
    },
    fonts: {
      title: 'GmarketSans',
      body: 'Pretendard',
      accent: 'GmarketSans',
    },
    defaultMusic: 'baby-lullaby',
    defaultTransition: 'fade',
    defaultEffect: 'kenburns-zoom-in',
    titleTemplate: '{name}의 성장 일기',
    defaultEnding: '{name}의 성장 이야기 📒\n매일매일 사랑해 💕',
    narrationPrompt: `당신은 아기 성장 앨범 영상의 나레이터입니다.
아기의 각 성장 단계를 사랑스럽게 담아주세요.
따뜻하고 다정한 톤으로 진행하세요.`,
    narrationStyle: 'gentle, loving, nostalgic',
    suggestedDuration: 120,
    suggestedPhotoCount: { min: 30, max: 80 },
    tags: ['성장', '아기', '앨범', '기록', '사랑'],
    premium: false,
    introStyles: [
      { type: 'floating', duration: 5, elements: ['title', 'subtitle', 'particles'], animation: { titleDelay: 1, subtitleDelay: 2.5, easing: 'easeOutSine' } },
      { type: 'fade-zoom', duration: 4, elements: ['title', 'date'], animation: { titleDelay: 0.5, subtitleDelay: 1.5, easing: 'easeOut' } },
    ],
    outroStyles: [
      { type: 'memories', duration: 6, elements: ['message', 'photos'], animation: { messageDelay: 0, photosDelay: 1.5, easing: 'easeOut' } },
      { type: 'timeline', duration: 6, elements: ['message', 'photos', 'credits'], animation: { messageDelay: 0, photosDelay: 1.5, easing: 'easeInOut' } },
    ],
    introPrompts: [
      '소중한 성장의 기록',
      '하루하루 자라는 우리 아기',
      '사랑으로 채워지는 성장 일기',
    ],
    outroPrompts: [
      '앞으로도 건강하게 자라렴',
      '매 순간이 소중한 추억',
      '영원히 사랑할게, 우리 아기',
    ],
  },
  {
    id: 'FAMILY_VACATION',
    name: '가족 여행',
    nameEn: 'Family Vacation',
    icon: '✈️',
    emoji: '🏖️',
    description: '함께 떠난 특별한 여행',
    category: 'family',
    subCategory: 'travel',
    colors: {
      primary: '#0EA5E9',
      secondary: '#38BDF8',
      accent: '#7DD3FC',
      background: '#F0F9FF',
      text: '#0C4A6E',
      gradient: 'linear-gradient(135deg, #0EA5E9 0%, #7DD3FC 100%)',
    },
    fonts: {
      title: 'GmarketSans',
      body: 'Pretendard',
      accent: 'GmarketSans',
    },
    defaultMusic: 'travel-adventure',
    defaultTransition: 'slideRight',
    defaultEffect: 'kenburns-pan-right',
    titleTemplate: '{destination} 가족 여행',
    defaultEnding: '함께여서 더 행복했던 여행! ✈️\n다음 여행도 기대됩니다 💕',
    narrationPrompt: `당신은 가족 여행 영상의 나레이터입니다.
가족과 함께한 여행의 즐거움과 추억을 담아주세요.
밝고 행복한 톤으로 진행하세요.`,
    narrationStyle: 'adventurous, joyful, family-oriented',
    suggestedDuration: 120,
    suggestedPhotoCount: { min: 30, max: 80 },
    tags: ['가족여행', '여행', '추억', '행복', '함께'],
    premium: false,
    introStyles: [
      { type: 'slide-up', duration: 4, elements: ['title', 'subtitle', 'gradient-bg'], animation: { titleDelay: 0.5, subtitleDelay: 1.5, easing: 'easeOut' } },
      { type: 'dynamic-zoom', duration: 4, elements: ['title', 'date'], animation: { titleDelay: 0.3, subtitleDelay: 1.2, easing: 'easeOut' } },
    ],
    outroStyles: [
      { type: 'photo-collage', duration: 5, elements: ['message', 'photos'], animation: { messageDelay: 0.5, photosDelay: 0, easing: 'easeOut' } },
      { type: 'flying-photos', duration: 5, elements: ['message', 'photos'], animation: { messageDelay: 0.5, photosDelay: 0, easing: 'easeInOut' } },
    ],
    introPrompts: [
      '함께 떠나는 특별한 여행',
      '가족과 함께하는 모험',
      '행복한 추억을 만드는 시간',
    ],
    outroPrompts: [
      '함께여서 더 빛났던 순간들',
      '다음 여행이 벌써 기대돼요',
      '가족과 함께한 최고의 시간',
    ],
  },
  {
    id: 'PARENTS_ANNIVERSARY',
    name: '부모님 결혼기념일',
    nameEn: 'Parents Anniversary',
    icon: '💑',
    emoji: '💝',
    description: '변함없는 사랑을 축하해요',
    category: 'family',
    subCategory: 'anniversary',
    colors: {
      primary: '#DC2626',
      secondary: '#EF4444',
      accent: '#FCA5A5',
      background: '#FEF2F2',
      text: '#7F1D1D',
      gradient: 'linear-gradient(135deg, #DC2626 0%, #FCA5A5 100%)',
    },
    fonts: {
      title: 'GmarketSans',
      body: 'Pretendard',
      accent: 'GmarketSans',
    },
    defaultMusic: 'anniversary-romantic',
    defaultTransition: 'crossDissolve',
    defaultEffect: 'kenburns-zoom-in',
    titleTemplate: '아버지 ♥ 어머니 결혼 {years}주년',
    defaultEnding: '결혼기념일을 축하드립니다! 💝\n변함없는 사랑에 감사드려요',
    narrationPrompt: `당신은 부모님 결혼기념일 영상의 감사를 담은 나레이터입니다.
부모님의 사랑과 헌신에 대한 감사를 진심으로 전달하세요.
따뜻하고 감사에 넘치는 톤으로 진행하세요.`,
    narrationStyle: 'grateful, respectful, loving',
    suggestedDuration: 90,
    suggestedPhotoCount: { min: 20, max: 50 },
    tags: ['결혼기념일', '부모님', '사랑', '감사', '축하'],
    premium: false,
    introStyles: [
      { type: 'elegant-fade', duration: 5, elements: ['title', 'subtitle', 'gradient-bg'], animation: { titleDelay: 1, subtitleDelay: 2.5, easing: 'easeInOut' } },
      { type: 'floating', duration: 5, elements: ['title', 'date', 'particles'], animation: { titleDelay: 1, subtitleDelay: 2.5, easing: 'easeOutSine' } },
    ],
    outroStyles: [
      { type: 'heart-gather', duration: 5, elements: ['message', 'photos'], animation: { messageDelay: 0.5, photosDelay: 1.5, easing: 'easeOut' } },
      { type: 'flower-bloom', duration: 5, elements: ['message', 'photos'], animation: { messageDelay: 0.5, photosDelay: 2, easing: 'easeOut' } },
    ],
    introPrompts: [
      '변함없는 사랑의 세월',
      '함께해서 더 빛나는 인생',
      '사랑으로 채워진 시간들',
    ],
    outroPrompts: [
      '영원히 행복하세요',
      '자녀들의 감사를 담아',
      '사랑하는 부모님께 축하를',
    ],
  },
  {
    id: 'GRANDPARENTS_BIRTHDAY',
    name: '조부모님 생신',
    nameEn: 'Grandparents Birthday',
    icon: '👴',
    emoji: '🎂',
    description: '존경과 사랑을 담아',
    category: 'family',
    subCategory: 'birthday',
    colors: {
      primary: '#92400E',
      secondary: '#B45309',
      accent: '#D97706',
      background: '#FFFBEB',
      text: '#78350F',
      gradient: 'linear-gradient(135deg, #92400E 0%, #D97706 100%)',
    },
    fonts: {
      title: 'GmarketSans',
      body: 'Pretendard',
      accent: 'GmarketSans',
    },
    defaultMusic: 'longevity-traditional',
    defaultTransition: 'crossDissolve',
    defaultEffect: 'kenburns-zoom-in',
    titleTemplate: '{name} 어르신 {age}세 생신',
    defaultEnding: '생신을 진심으로 축하드립니다! 🎂\n항상 건강하세요 💕',
    narrationPrompt: `당신은 조부모님 생신 영상의 공경하는 나레이터입니다.
어르신에 대한 존경과 감사의 마음을 정성껏 전달하세요.
공경하고 따뜻한 톤으로 진행하세요.`,
    narrationStyle: 'respectful, warm, grateful',
    suggestedDuration: 60,
    suggestedPhotoCount: { min: 15, max: 40 },
    tags: ['생신', '조부모님', '존경', '감사', '장수'],
    premium: false,
    introStyles: [
      { type: 'elegant-fade', duration: 5, elements: ['title', 'subtitle', 'gradient-bg'], animation: { titleDelay: 1, subtitleDelay: 2.5, easing: 'easeInOut' } },
      { type: 'fade-zoom', duration: 4, elements: ['title', 'date'], animation: { titleDelay: 0.5, subtitleDelay: 1.5, easing: 'easeOut' } },
    ],
    outroStyles: [
      { type: 'flower-bloom', duration: 5, elements: ['message', 'photos'], animation: { messageDelay: 0.5, photosDelay: 2, easing: 'easeOut' } },
      { type: 'thank-you', duration: 5, elements: ['message', 'credits'], animation: { messageDelay: 0, photosDelay: 2, easing: 'easeInOut' } },
    ],
    introPrompts: [
      '존경과 사랑을 담아',
      '오래오래 건강하세요',
      '가족들의 진심 어린 축하',
    ],
    outroPrompts: [
      '건강하게 오래오래 곁에 계세요',
      '감사하고 사랑합니다',
      '복 많이 받으세요',
    ],
  },
  {
    id: 'RETIREMENT',
    name: '정년퇴직',
    nameEn: 'Retirement',
    icon: '🏆',
    emoji: '🎉',
    description: '수고하셨습니다, 새로운 시작',
    category: 'family',
    subCategory: 'celebration',
    colors: {
      primary: '#B45309',
      secondary: '#D97706',
      accent: '#FBBF24',
      background: '#FFFBEB',
      text: '#78350F',
      gradient: 'linear-gradient(135deg, #B45309 0%, #FBBF24 100%)',
    },
    fonts: {
      title: 'GmarketSans',
      body: 'Pretendard',
      accent: 'GmarketSans',
    },
    defaultMusic: 'retirement-honorable',
    defaultTransition: 'crossDissolve',
    defaultEffect: 'kenburns-pan-right',
    titleTemplate: '{name}님의 정년퇴직을 축하합니다',
    defaultEnding: '오랜 세월 수고 많으셨습니다! 🏆\n앞으로의 인생도 행복하시길 바랍니다 💕',
    narrationPrompt: `당신은 정년퇴직 축하 영상의 존경을 담은 나레이터입니다.
수십 년간의 헌신과 노력에 대한 감사를 전달하세요.
존경하고 축하하는 톤으로 진행하세요.`,
    narrationStyle: 'honorable, grateful, celebratory',
    suggestedDuration: 120,
    suggestedPhotoCount: { min: 25, max: 60 },
    tags: ['퇴직', '정년', '축하', '감사', '새출발'],
    premium: true,
    introStyles: [
      { type: 'cinematic', duration: 6, elements: ['title', 'subtitle', 'gradient-bg'], animation: { titleDelay: 1.5, subtitleDelay: 3, easing: 'easeInOut' } },
      { type: 'reveal', duration: 5, elements: ['title', 'date'], animation: { titleDelay: 0.5, subtitleDelay: 2, easing: 'easeOut' } },
    ],
    outroStyles: [
      { type: 'scroll-credits', duration: 7, elements: ['message', 'credits', 'photos'], animation: { messageDelay: 0, photosDelay: 2, easing: 'linear' } },
      { type: 'fireworks', duration: 5, elements: ['message', 'photos'], animation: { messageDelay: 0.5, photosDelay: 2, easing: 'easeOut' } },
    ],
    introPrompts: [
      '헌신과 열정의 세월을 돌아보며',
      '수고 많으셨습니다',
      '새로운 시작을 축하하며',
    ],
    outroPrompts: [
      '제2의 인생을 응원합니다',
      '건강하고 행복하세요',
      '감사와 존경을 담아',
    ],
  },
  {
    id: 'NEW_HOME',
    name: '집들이',
    nameEn: 'Housewarming',
    icon: '🏠',
    emoji: '🎊',
    description: '새 보금자리를 축하해요',
    category: 'family',
    subCategory: 'celebration',
    colors: {
      primary: '#059669',
      secondary: '#10B981',
      accent: '#34D399',
      background: '#ECFDF5',
      text: '#064E3B',
      gradient: 'linear-gradient(135deg, #059669 0%, #34D399 100%)',
    },
    fonts: {
      title: 'GmarketSans',
      body: 'Pretendard',
      accent: 'GmarketSans',
    },
    defaultMusic: 'housewarming-joyful',
    defaultTransition: 'slideRight',
    defaultEffect: 'kenburns-pan-right',
    titleTemplate: '{family} 가족의 새 보금자리',
    defaultEnding: '새 집에서 행복하세요! 🏠\n축하합니다! 🎊',
    narrationPrompt: `당신은 집들이 영상의 축하하는 나레이터입니다.
새 보금자리에서의 행복을 기원하는 마음을 담아주세요.
밝고 축하하는 톤으로 진행하세요.`,
    narrationStyle: 'celebratory, warm, hopeful',
    suggestedDuration: 60,
    suggestedPhotoCount: { min: 15, max: 35 },
    tags: ['집들이', '새집', '보금자리', '축하', '행복'],
    premium: false,
    introStyles: [
      { type: 'reveal', duration: 4, elements: ['title', 'subtitle', 'gradient-bg'], animation: { titleDelay: 0.5, subtitleDelay: 2, easing: 'easeOut' } },
      { type: 'slide-up', duration: 4, elements: ['title', 'date'], animation: { titleDelay: 0.5, subtitleDelay: 1.5, easing: 'easeOut' } },
    ],
    outroStyles: [
      { type: 'confetti', duration: 4, elements: ['message', 'photos'], animation: { messageDelay: 0.5, photosDelay: 1.5, easing: 'easeOut' } },
      { type: 'photo-collage', duration: 5, elements: ['message', 'photos'], animation: { messageDelay: 0.5, photosDelay: 0, easing: 'easeOut' } },
    ],
    introPrompts: [
      '새로운 시작을 축하하며',
      '행복이 가득할 보금자리',
      '꿈에 그리던 우리 집',
    ],
    outroPrompts: [
      '새 집에서 행복하세요',
      '축복이 가득하길 바랍니다',
      '항상 웃음이 넘치는 집이 되길',
    ],
  },
  {
    id: 'PET_MEMORIAL',
    name: '반려동물 추모',
    nameEn: 'Pet Memorial',
    icon: '🐾',
    emoji: '🌈',
    description: '영원한 친구를 기억해요',
    category: 'family',
    subCategory: 'memorial',
    colors: {
      primary: '#6B7280',
      secondary: '#9CA3AF',
      accent: '#D1D5DB',
      background: '#F9FAFB',
      text: '#374151',
      gradient: 'linear-gradient(135deg, #6B7280 0%, #D1D5DB 100%)',
    },
    fonts: {
      title: 'GmarketSans',
      body: 'Pretendard',
      accent: 'GmarketSans',
    },
    defaultMusic: 'memorial-peaceful',
    defaultTransition: 'fade',
    defaultEffect: 'kenburns-zoom-in',
    titleTemplate: '사랑하는 {name}를 기억하며',
    defaultEnding: '무지개 다리 건너 편안히 쉬렴 🌈\n영원히 사랑해, {name} 🐾💕',
    narrationPrompt: `당신은 반려동물 추모 영상의 진심 어린 나레이터입니다.
반려동물과의 소중한 추억과 감사의 마음을 담아주세요.
따뜻하고 위로가 되는 톤으로 진행하세요.`,
    narrationStyle: 'gentle, comforting, loving',
    suggestedDuration: 90,
    suggestedPhotoCount: { min: 20, max: 50 },
    tags: ['추모', '반려동물', '펫', '기억', '사랑'],
    premium: false,
    introStyles: [
      { type: 'elegant-fade', duration: 5, elements: ['title', 'subtitle', 'gradient-bg'], animation: { titleDelay: 1, subtitleDelay: 2.5, easing: 'easeInOut' } },
      { type: 'floating', duration: 5, elements: ['title', 'particles'], animation: { titleDelay: 1, subtitleDelay: 2.5, easing: 'easeOutSine' } },
    ],
    outroStyles: [
      { type: 'fade-out', duration: 5, elements: ['message', 'photos'], animation: { messageDelay: 0, photosDelay: 2, easing: 'easeInOut' } },
      { type: 'memories', duration: 6, elements: ['message', 'photos'], animation: { messageDelay: 0, photosDelay: 1.5, easing: 'easeOut' } },
    ],
    introPrompts: [
      '영원히 기억될 소중한 친구',
      '함께했던 행복한 시간들',
      '사랑으로 가득했던 날들',
    ],
    outroPrompts: [
      '무지개 다리 건너 편안히',
      '영원히 마음속에 함께',
      '사랑해, 우리의 영원한 친구',
    ],
  },
  {
    id: 'FAMILY_REUNION',
    name: '가족 모임/명절',
    nameEn: 'Family Reunion',
    icon: '👨‍👩‍👧‍👦',
    emoji: '🎊',
    description: '함께 모인 소중한 시간',
    category: 'family',
    subCategory: 'gathering',
    colors: {
      primary: '#DC2626',
      secondary: '#EF4444',
      accent: '#FCA5A5',
      background: '#FEF2F2',
      text: '#7F1D1D',
      gradient: 'linear-gradient(135deg, #DC2626 0%, #FCA5A5 100%)',
    },
    fonts: {
      title: 'GmarketSans',
      body: 'Pretendard',
      accent: 'GmarketSans',
    },
    defaultMusic: 'family-gathering',
    defaultTransition: 'crossDissolve',
    defaultEffect: 'kenburns-zoom-in',
    titleTemplate: '{year} {occasion} 가족 모임',
    defaultEnding: '함께해서 행복했습니다! 👨‍👩‍👧‍👦\n다음 모임도 기대할게요 💕',
    narrationPrompt: `당신은 가족 모임 영상의 따뜻한 나레이터입니다.
가족과 함께한 소중한 시간과 정을 담아주세요.
따뜻하고 정감 있는 톤으로 진행하세요.`,
    narrationStyle: 'warm, family-oriented, joyful',
    suggestedDuration: 90,
    suggestedPhotoCount: { min: 20, max: 50 },
    tags: ['가족모임', '명절', '추석', '설날', '함께'],
    premium: false,
    introStyles: [
      { type: 'fade-zoom', duration: 4, elements: ['title', 'subtitle', 'gradient-bg'], animation: { titleDelay: 0.5, subtitleDelay: 1.5, easing: 'easeOut' } },
      { type: 'floating', duration: 4, elements: ['title', 'date', 'particles'], animation: { titleDelay: 0.5, subtitleDelay: 1.5, easing: 'easeOutSine' } },
    ],
    outroStyles: [
      { type: 'photo-collage', duration: 5, elements: ['message', 'photos'], animation: { messageDelay: 0.5, photosDelay: 0, easing: 'easeOut' } },
      { type: 'heart-gather', duration: 5, elements: ['message', 'photos'], animation: { messageDelay: 0.5, photosDelay: 1.5, easing: 'easeOut' } },
    ],
    introPrompts: [
      '함께 모인 소중한 시간',
      '사랑하는 가족들과 함께',
      '행복이 넘치는 모임',
    ],
    outroPrompts: [
      '다음 모임도 기대할게요',
      '가족이라서 행복합니다',
      '사랑하는 우리 가족',
    ],
  },
  {
    id: 'PREGNANCY_JOURNEY',
    name: '임신/출산 여정',
    nameEn: 'Pregnancy Journey',
    icon: '🤰',
    emoji: '👶',
    description: '새 생명을 기다리는 여정',
    category: 'family',
    subCategory: 'baby',
    colors: {
      primary: '#F9A8D4',
      secondary: '#FBCFE8',
      accent: '#FCE7F3',
      background: '#FDF2F8',
      text: '#9D174D',
      gradient: 'linear-gradient(135deg, #F9A8D4 0%, #FCE7F3 100%)',
    },
    fonts: {
      title: 'GmarketSans',
      body: 'Pretendard',
      accent: 'GmarketSans',
    },
    defaultMusic: 'pregnancy-hopeful',
    defaultTransition: 'fade',
    defaultEffect: 'kenburns-zoom-in',
    titleTemplate: '{baby}를 기다리며',
    defaultEnding: '건강하게 태어나줘서 고마워! 👶\n사랑해, 우리 아기 💕',
    narrationPrompt: `당신은 임신/출산 여정 영상의 나레이터입니다.
새 생명을 기다리는 설렘과 기쁨을 담아주세요.
따뜻하고 희망찬 톤으로 진행하세요.`,
    narrationStyle: 'hopeful, loving, blessed',
    suggestedDuration: 120,
    suggestedPhotoCount: { min: 25, max: 60 },
    tags: ['임신', '출산', '아기', '여정', '축복'],
    premium: true,
    introStyles: [
      { type: 'floating', duration: 5, elements: ['title', 'subtitle', 'particles'], animation: { titleDelay: 1, subtitleDelay: 2.5, easing: 'easeOutSine' } },
      { type: 'fade-zoom', duration: 4, elements: ['title', 'date', 'gradient-bg'], animation: { titleDelay: 0.5, subtitleDelay: 1.5, easing: 'easeOut' } },
    ],
    outroStyles: [
      { type: 'heart-gather', duration: 5, elements: ['message', 'photos'], animation: { messageDelay: 0.5, photosDelay: 1.5, easing: 'easeOut' } },
      { type: 'timeline', duration: 6, elements: ['message', 'photos', 'credits'], animation: { messageDelay: 0, photosDelay: 1.5, easing: 'easeInOut' } },
    ],
    introPrompts: [
      '새 생명을 기다리는 설렘',
      '사랑으로 가득한 여정',
      '축복받은 우리의 이야기',
    ],
    outroPrompts: [
      '건강하게 태어나줘서 고마워',
      '사랑으로 키울게',
      '세상에서 가장 소중한 너',
    ],
  },
  {
    id: 'MEMORIAL',
    name: '추모 영상',
    nameEn: 'Memorial',
    icon: '🕯️',
    emoji: '🌹',
    description: '소중한 분을 기억합니다',
    category: 'family',
    subCategory: 'memorial',
    colors: {
      primary: '#4B5563',
      secondary: '#6B7280',
      accent: '#9CA3AF',
      background: '#F3F4F6',
      text: '#1F2937',
      gradient: 'linear-gradient(135deg, #4B5563 0%, #9CA3AF 100%)',
    },
    fonts: {
      title: 'GmarketSans',
      body: 'Pretendard',
      accent: 'GmarketSans',
    },
    defaultMusic: 'memorial-peaceful',
    defaultTransition: 'fade',
    defaultEffect: 'kenburns-zoom-in',
    titleTemplate: '사랑하는 {name}을 기억하며',
    defaultEnding: '영원히 우리 마음속에 🕯️\n사랑합니다, 그리고 감사합니다 💐',
    narrationPrompt: `당신은 추모 영상의 진심 어린 나레이터입니다.
고인에 대한 사랑과 추억을 정성껏 담아주세요.
따뜻하고 위로가 되는 톤으로 진행하세요.`,
    narrationStyle: 'reverent, comforting, loving',
    suggestedDuration: 120,
    suggestedPhotoCount: { min: 20, max: 50 },
    tags: ['추모', '기억', '사랑', '감사', '영원'],
    premium: true,
    introStyles: [
      { type: 'elegant-fade', duration: 6, elements: ['title', 'subtitle', 'gradient-bg'], animation: { titleDelay: 1.5, subtitleDelay: 3.5, easing: 'easeInOut' } },
      { type: 'fade-zoom', duration: 5, elements: ['title', 'date'], animation: { titleDelay: 1, subtitleDelay: 2.5, easing: 'easeInOut' } },
    ],
    outroStyles: [
      { type: 'sunset', duration: 6, elements: ['message', 'photos'], animation: { messageDelay: 0, photosDelay: 2, easing: 'easeInOut' } },
      { type: 'memories', duration: 6, elements: ['message', 'photos'], animation: { messageDelay: 0, photosDelay: 1.5, easing: 'easeOut' } },
    ],
    introPrompts: [
      '영원히 기억될 소중한 분',
      '사랑으로 가득했던 시간들',
      '함께했던 아름다운 순간들',
    ],
    outroPrompts: [
      '영원히 마음속에 함께',
      '사랑하고 감사합니다',
      '편히 쉬세요',
    ],
  },
];
